### PR TITLE
treehouses sshkey delete partial match (fixes #467)

### LINKED ISSUE #467: sshkey accepts any input and deletes any key that matches input
```
root@treehouses:~/cli# ./cli.sh sshkey add "hello"
====== Added to 'pi' and 'root' user's authorized_keys ======
hello
root@treehouses:~/cli# ./cli.sh sshkey list
==== root keys ====
hello
==== pi keys ====
hello
root@treehouses:~/cli# ./cli.sh sshkey delete "h"
h is deleted.
root@treehouses:~/cli# ./cli.sh sshkey list
==== root keys ====
==== pi keys ====
root@treehouses:~/cli# 


```

### PR DESCRIPTION
**Pull request by kjong**
Fixes #467

### CODE REVIEW

**Comment by irisb1701** [comment]
```
==== pi keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOQehuSI7U6XzeSJyEJxZK2NCOSXdE9x8s73tznWodgOO+arUpy6bjpcD33QwZxUN1R96lzuYc3sqpC3gDennwgTi94dHBo5AZjHE6LL+5ya2LpIr94iM4FoXX1BkGhF2hs8bNcqkcSvXLqmtI0Z/yAa4FP1riYM2MG/6F5QS7GEhDJf0t+u2SUSs3S24aNjQtgBhmWMfk1SSV1AGZ/CKN12iy75OjIWEIqph1Jjr8Efi/tGEZNks4qkQkIkK3fb+NMJkx93kuTzJ818OjWefVIVgz0GQEOOXQiIKj3frusyhNMKqeC9dZwYnQg1ehsMd6oxvZKZoQ06KAFjmutu8d vmnet8
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXWXoccW1OvYWFaAF4A0qWREFUZActnfdJy2vxlK1hXghkPj4hO0uJXBarRzSVtvy/NXOWw9aSjFiskVzjWqw2tyU+q8iYPAsCThJ0L8+82vSJei2hJmJ4LuN9V58v+BM7gJXSK3CbLR34DDC6WAEBV98kVfqDr3705wApxe8SrjXIME6xLIpnMtbHzzmRbvVv+EYK4izu7/fWT2a+2DFo8y1WqentJynoPAv2OGOoduqUOrsHrfyZEmEYGqxULy4GqhS8hzUveCz4U0chS3mfy6Qf7v77Lmf+FqdbKEKFtRkm4061XgVsU0qEKhVePXNmoD1iPysPJIb9B8g3BHf+zk/ICFy7juPnDQ22Q3COLQUj7yx8ZNqvBijMzAXFhIt9X55EnrrNdAzNlgfZpXUqKzOu+El3HwoAs6OD8bm5Di8z6K4wv0xlpuPS0RmPy/Mk6FWJT57DS/HVlF5mB49oAQnUAGTEgZ6TZQj5Q385UU6js0KgGvolRfIKQ06pQlSxVJtmUgzTBCX8yKW+zYzbXpIdgFSsjzA4MtjPD81TC0QINeMxCherDp5RFEeSZd0NMdF5p/esKvrQFrA6ITwxzM2vs3cNy1W1h2HPQkdJoOpRHYtkN6kOTJMRYj22g9S3QKKDP8FrY8L3Dj55D38NIE58TUst3RYOxaZlep/DCQ== vmnet8
root@treehouses:/home/pi/cli# treehouses sshkey delete "t"
t is deleted.
root@treehouses:/home/pi/cli# treehouses sshkey list
==== root keys ====
==== pi keys ====
root@treehouses:/home/pi/cli#
```

**Comment by kjong** [comment]
```
root@kjong:~/cli# ./cli.sh sshkey github adduser vmnet8
====== Added to 'pi' and 'root' user's authorized_keys ======
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOQehuSI7U6XzeSJyEJxZK2NCOSXdE9x8s73tznWodgOO+ arUpy6bjpcD33QwZxUN1R96lzuYc3sqpC3gDennwgTi94dHBo5AZjHE6LL+5ya2LpIr94iM4FoXX1BkGhF2h s8bNcqkcSvXLqmtI0Z/yAa4FP1riYM2MG/6F5QS7GEhDJf0t+u2SUSs3S24aNjQtgBhmWMfk1SSV1AGZ/CKN 12iy75OjIWEIqph1Jjr8Efi/tGEZNks4qkQkIkK3fb+NMJkx93kuTzJ818OjWefVIVgz0GQEOOXQiIKj3fru syhNMKqeC9dZwYnQg1ehsMd6oxvZKZoQ06KAFjmutu8d vmnet8
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXWXoccW1OvYWFaAF4A0qWREFUZActnfdJy2vxlK1hXghk Pj4hO0uJXBarRzSVtvy/NXOWw9aSjFiskVzjWqw2tyU+q8iYPAsCThJ0L8+82vSJei2hJmJ4LuN9V58v+BM7 gJXSK3CbLR34DDC6WAEBV98kVfqDr3705wApxe8SrjXIME6xLIpnMtbHzzmRbvVv+EYK4izu7/fWT2a+2DFo 8y1WqentJynoPAv2OGOoduqUOrsHrfyZEmEYGqxULy4GqhS8hzUveCz4U0chS3mfy6Qf7v77Lmf+FqdbKEKF tRkm4061XgVsU0qEKhVePXNmoD1iPysPJIb9B8g3BHf+zk/ICFy7juPnDQ22Q3COLQUj7yx8ZNqvBijMzAXF hIt9X55EnrrNdAzNlgfZpXUqKzOu+El3HwoAs6OD8bm5Di8z6K4wv0xlpuPS0RmPy/Mk6FWJT57DS/HVlF5m B49oAQnUAGTEgZ6TZQj5Q385UU6js0KgGvolRfIKQ06pQlSxVJtmUgzTBCX8yKW+zYzbXpIdgFSsjzA4MtjP D81TC0QINeMxCherDp5RFEeSZd0NMdF5p/esKvrQFrA6ITwxzM2vs3cNy1W1h2HPQkdJoOpRHYtkN6kOTJMR Yj22g9S3QKKDP8FrY8L3Dj55D38NIE58TUst3RYOxaZlep/DCQ== vmnet8                          
root@kjong:~/cli# ./cli.sh sshkey delete "t"
t not found in root keys.
t not found in pi keys.
root@kjong:~/cli# ./cli.sh sshkey list
==== root keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOQehuSI7U6XzeSJyEJxZK2NCOSXdE9x8s73tznWodgOO+ arUpy6bjpcD33QwZxUN1R96lzuYc3sqpC3gDennwgTi94dHBo5AZjHE6LL+5ya2LpIr94iM4FoXX1BkGhF2h s8bNcqkcSvXLqmtI0Z/yAa4FP1riYM2MG/6F5QS7GEhDJf0t+u2SUSs3S24aNjQtgBhmWMfk1SSV1AGZ/CKN 12iy75OjIWEIqph1Jjr8Efi/tGEZNks4qkQkIkK3fb+NMJkx93kuTzJ818OjWefVIVgz0GQEOOXQiIKj3fru syhNMKqeC9dZwYnQg1ehsMd6oxvZKZoQ06KAFjmutu8d vmnet8
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXWXoccW1OvYWFaAF4A0qWREFUZActnfdJy2vxlK1hXghk Pj4hO0uJXBarRzSVtvy/NXOWw9aSjFiskVzjWqw2tyU+q8iYPAsCThJ0L8+82vSJei2hJmJ4LuN9V58v+BM7 gJXSK3CbLR34DDC6WAEBV98kVfqDr3705wApxe8SrjXIME6xLIpnMtbHzzmRbvVv+EYK4izu7/fWT2a+2DFo 8y1WqentJynoPAv2OGOoduqUOrsHrfyZEmEYGqxULy4GqhS8hzUveCz4U0chS3mfy6Qf7v77Lmf+FqdbKEKF tRkm4061XgVsU0qEKhVePXNmoD1iPysPJIb9B8g3BHf+zk/ICFy7juPnDQ22Q3COLQUj7yx8ZNqvBijMzAXF hIt9X55EnrrNdAzNlgfZpXUqKzOu+El3HwoAs6OD8bm5Di8z6K4wv0xlpuPS0RmPy/Mk6FWJT57DS/HVlF5m B49oAQnUAGTEgZ6TZQj5Q385UU6js0KgGvolRfIKQ06pQlSxVJtmUgzTBCX8yKW+zYzbXpIdgFSsjzA4MtjP D81TC0QINeMxCherDp5RFEeSZd0NMdF5p/esKvrQFrA6ITwxzM2vs3cNy1W1h2HPQkdJoOpRHYtkN6kOTJMR Yj22g9S3QKKDP8FrY8L3Dj55D38NIE58TUst3RYOxaZlep/DCQ== vmnet8                          
==== pi keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOQehuSI7U6XzeSJyEJxZK2NCOSXdE9x8s73tznWodgOO+ arUpy6bjpcD33QwZxUN1R96lzuYc3sqpC3gDennwgTi94dHBo5AZjHE6LL+5ya2LpIr94iM4FoXX1BkGhF2h s8bNcqkcSvXLqmtI0Z/yAa4FP1riYM2MG/6F5QS7GEhDJf0t+u2SUSs3S24aNjQtgBhmWMfk1SSV1AGZ/CKN 12iy75OjIWEIqph1Jjr8Efi/tGEZNks4qkQkIkK3fb+NMJkx93kuTzJ818OjWefVIVgz0GQEOOXQiIKj3fru syhNMKqeC9dZwYnQg1ehsMd6oxvZKZoQ06KAFjmutu8d vmnet8
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXWXoccW1OvYWFaAF4A0qWREFUZActnfdJy2vxlK1hXghk Pj4hO0uJXBarRzSVtvy/NXOWw9aSjFiskVzjWqw2tyU+q8iYPAsCThJ0L8+82vSJei2hJmJ4LuN9V58v+BM7 gJXSK3CbLR34DDC6WAEBV98kVfqDr3705wApxe8SrjXIME6xLIpnMtbHzzmRbvVv+EYK4izu7/fWT2a+2DFo 8y1WqentJynoPAv2OGOoduqUOrsHrfyZEmEYGqxULy4GqhS8hzUveCz4U0chS3mfy6Qf7v77Lmf+FqdbKEKF tRkm4061XgVsU0qEKhVePXNmoD1iPysPJIb9B8g3BHf+zk/ICFy7juPnDQ22Q3COLQUj7yx8ZNqvBijMzAXF hIt9X55EnrrNdAzNlgfZpXUqKzOu+El3HwoAs6OD8bm5Di8z6K4wv0xlpuPS0RmPy/Mk6FWJT57DS/HVlF5m B49oAQnUAGTEgZ6TZQj5Q385UU6js0KgGvolRfIKQ06pQlSxVJtmUgzTBCX8yKW+zYzbXpIdgFSsjzA4MtjP D81TC0QINeMxCherDp5RFEeSZd0NMdF5p/esKvrQFrA6ITwxzM2vs3cNy1W1h2HPQkdJoOpRHYtkN6kOTJMR Yj22g9S3QKKDP8FrY8L3Dj55D38NIE58TUst3RYOxaZlep/DCQ== vmnet8

**Comment by kjong** [comment]
I can't seem to recreate the issue.

**Comment by irisb1701** [comment]
So I was just forgetting to use ./cli.sh, tested it again and it's not an issue.

Ran into another, wasn't able to delete an ssh key

```
root@treehouses:/home/pi/cli# ./cli.sh sshkey list
==== root keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi
==== pi keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi
root@treehouses:/home/pi/cli# 
root@treehouses:/home/pi/cli# 
root@treehouses:/home/pi/cli# ./cli.sh sshkey delete "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw=="
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== not found in root keys.
``` 

```
root@treehouses:/home/pi/cli# ./cli.sh sshkey delete "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi"
```
```
sed: -e expression #1, char 196: unknown command: `O'
```
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi is deleted from root keys.
sed: -e expression #1, char 196: unknown command: `O'
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi is deleted from pi keys.
```
```
root@treehouses:/home/pi/cli# ./cli.sh sshkey list
==== root keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi
==== pi keys ====
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== dogi
root@treehouses:/home/pi/cli# 
```

**Comment by pattanawadee88** [comment]
I got an error 
```
root@treehouses:~/cli# ./cli.sh sshkey delete "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7kF3yPSG6LkQwrE33Aoi9zvslm+lyrreVgPbHbYnSXR/QDJTpCC3pn1wcy8e1T87xQNycitdLlZ/sL7rVozV1OgiF7hjok0l+49ZzUbK+kU5D/ERYU3eg+GEF49IzZ26E3DEJA7E5VDIxL1QnqO2J0RMhekN4I+aSxkaEHXGIdAFPOA4PbRo/DhEyEKdcEHVLd3zXFtG4Rbbv1smenXyMq4P0fCZf7+Dei03IkE+9yhTWrioSXw1sLLBHvp1xHt+iwHq5th16a5WmlGjJ3WZfNQ+IDhH9ozCYG/vVz5PuLbd+htPDZh+0sWpH2abynPzmDVROCgIw+eN8XjN8IN8N saraive16"
sed: -e expression #1, char 88: extra characters after command
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7kF3yPSG6LkQwrE33Aoi9zvslm+lyrreVgPbHbYnSXR/QDJTpCC3pn1wcy8e1T87xQNycitdLlZ/sL7rVozV1OgiF7hjok0l+49ZzUbK+kU5D/ERYU3eg+GEF49IzZ26E3DEJA7E5VDIxL1QnqO2J0RMhekN4I+aSxkaEHXGIdAFPOA4PbRo/DhEyEKdcEHVLd3zXFtG4Rbbv1smenXyMq4P0fCZf7+Dei03IkE+9yhTWrioSXw1sLLBHvp1xHt+iwHq5th16a5WmlGjJ3WZfNQ+IDhH9ozCYG/vVz5PuLbd+htPDZh+0sWpH2abynPzmDVROCgIw+eN8XjN8IN8N saraive16 is deleted from root keys.
sed: -e expression #1, char 88: extra characters after command
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7kF3yPSG6LkQwrE33Aoi9zvslm+lyrreVgPbHbYnSXR/QDJTpCC3pn1wcy8e1T87xQNycitdLlZ/sL7rVozV1OgiF7hjok0l+49ZzUbK+kU5D/ERYU3eg+GEF49IzZ26E3DEJA7E5VDIxL1QnqO2J0RMhekN4I+aSxkaEHXGIdAFPOA4PbRo/DhEyEKdcEHVLd3zXFtG4Rbbv1smenXyMq4P0fCZf7+Dei03IkE+9yhTWrioSXw1sLLBHvp1xHt+iwHq5th16a5WmlGjJ3WZfNQ+IDhH9ozCYG/vVz5PuLbd+htPDZh+0sWpH2abynPzmDVROCgIw+eN8XjN8IN8N saraive16 is deleted from pi keys.
root@treehouses:~/cli# 
```

**Comment by irisb1701** [comment]
Works for me as well! Only thing I would change is to not repeat the entire key again in the "key deleted" message.

**Comment by kjong** [comment]
Would a simple message like `Key has been deleted.` be better?

**Comment by irisb1701** [comment]
> Would a simple message like Key has been deleted. be better?

yep!

**Pull request merged**
