### PR TITLE
append output to log

### PR DESCRIPTION
**Pull request by 4ndrej**
append both stdout and stderr systemctl output to /var/log/treehouses

### CODE REVIEW

**Comment by 4ndrej** [comment]
well, you can use https://linux.die.net/man/8/logrotate with options:
compress
size 32k
rotate 2
copytruncate
but this is not directly related to this issue.
However, I created the config for you so you only have to put the config on the right place in /etc/logrotate.d/treehouses

**Comment by 4ndrej** [comment]
> Could you help to create the PR for that issue as well?

Well, this should be easy since logrotate daemon is standard linux/gnu stuff for ages, but I am not aware of your operating system flavour enough to make suggestions about package installation. What OS do you use?

**Comment by empeje** [comment]
We're using Raspbian - a Debian flavor OS for Raspberry Pi.

Please check https://github.com/treehouses/builder

**Comment by 4ndrej** [comment]
according to package list of raspbian stretch lite https://gist.github.com/n8henrie/a11ca9bdfee34e73976fdbcdea448f07 there is logrotate included so just copy that config file templates/logrotate.d/treehouses to the /etc/logrotate.d/treehouses and you are set.

**Comment by empeje** [comment]
Okay cool, I think I'll accept this PR. Thank you for contributing to @treehouses/cli

**Comment by i5o** [comment]
Hey, thanks for the contribution. 

However, I see you reated a rotate.d file, is it going to be needed?
If not can you please remove it?

Thanks :)

**Comment by 4ndrej** [comment]
@i5o "rotate.d file" is not changed, it does not exist at all.
I have no deep understanding of your build system, so I put desired logrotate config file to `templates/logrotate.d/treehouses`.
It should be moved to `/etc/logrotate.d/treehouses` in your target image. Maybe that should go to [treehouses/builder](https://github.com/treehouses/builder) repo.

**Comment by i5o** [comment]
I meant https://github.com/treehouses/cli/pull/192/files#diff-88949b9b385c03328ba4ca8c625511a5 @4ndrej.

And as you pointed out, yes, it may need to be on @treehouses/builder 	, but lets wait for @dogi 	for confirmation.

but it's a yes for me for it being in builder.

**Comment by empeje** [comment]
@dogi please help to check

cc: @4ndrej

**Comment by 4ndrej** [comment]
@dogi, no conflicts here
log to ramdisk to ease the sdcard wear
rotate logs to match space limit

**Comment by 4ndrej** [comment]
well..
a year ago this was relevant
now it is not

**Pull request closed without merging**
