### PR TITLE
treehouses remote commands (fixes #829)

### LINKED ISSUE #829: treehouses remote commands?
a way to output all static tab completion commands possible
from _treehouses
into a list

https://github.com/treehouses/cli/issues/826

### PR DESCRIPTION
**Pull request by kjong**
Fixes #829

Not sure if this is the approach @dogi was looking for.

```
root@kjong:~/cli# ./cli.sh remote commands
ap aphidden apchannel blocker bluetooth bluetoothid bootoption bridge burn button camera clone container coralenv cron defaul t detect detectrpi discover ethernet expandfs feedback help image internet led locale log memory networkmode ntp openvpn pass word rebootneeded reboots rename restore rtc sdbench services speedtest ssh sshkey sshtunnel staticwifi temperature timezone  tor upgrade usb verbose version vnc wifi wificountry wifihidden wifistatus
root@kjong:~/cli# ./cli.sh remote commands sshkey
add list delete deleteall addgithubusername deletegithubusername addgithubgroup
```

### CODE REVIEW

**Comment by LordJashin32** [comment]
I'm thinking of doing some sorta grep on examples.

**Comment by kjong** [comment]
[commands.txt](https://github.com/treehouses/cli/files/4362399/commands.txt)

**Comment by LordJashin32** [comment]
> [commands.txt](https://github.com/treehouses/cli/files/4362399/commands.txt)
> 
> Missing some commands for services.

Yeah. I think there's no way to avoid not doing it manually. I looked into auto completion and there's no way to just list everything u want.
We can either do loop upon loop on all the variables inside _treehouses, OR have a manual huge string with all the commands in it. I think huge list of manual will be easier to maintain. But this is how Srihari wanted the list to look. Referring to the one you posted. Maybe we put this giant string variable inside _treehouses? So we don't have to edit more files.

**Comment by LordJashin32** [comment]
> > [commands.txt](https://github.com/treehouses/cli/files/4362399/commands.txt)
> > Missing some commands for services.
> 
> Yeah. I think there's no way to avoid not doing it manually. I looked into auto completion and there's no way to just list everything u want.
> We can either do loop upon loop on all the variables inside _treehouses, OR have a manual huge string with all the commands in it. I think huge list of manual will be easier to maintain. But this is how Srihari wanted the list to look. Referring to the one you posted. Maybe we put this giant string variable inside _treehouses? So we don't have to edit more files.

**Comment by kjong** [comment]
> > [commands.txt](https://github.com/treehouses/cli/files/4362399/commands.txt)
> > Missing some commands for services.
> 
> Yeah. I think there's no way to avoid not doing it manually. I looked into auto completion and there's no way to just list everything u want.
> We can either do loop upon loop on all the variables inside _treehouses, OR have a manual huge string with all the commands in it. I think huge list of manual will be easier to maintain. But this is how Srihari wanted the list to look. Referring to the one you posted. Maybe we put this giant string variable inside _treehouses? So we don't have to edit more files.

Yeah I used a script to get the list but to get the second and third level commands it would require like 4 or 5 nested for loops. There's probably a smarter way to do it.

**Comment by LordJashin32** [comment]
Test script commands
```
root@treehouses:/home/pi/Templates/cli/tests# ./test-cli.sh
 -  ap local test1 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  ap local test2 password (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  ap internet test3 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  ap internet test4 password (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  ap internet test5 password --ip=192.168.2.24 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  apchannel (skipped: You are using Wifi and SSH)
 -  apchannel 6 (skipped: You are using Wifi and SSH)
 -  aphidden local test123 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  aphidden local test123 password (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  aphidden internet test321 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  aphidden internet test321 password (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 -  aphidden internet test321 password --ip=192.168.2.24 (check ap...press any key to continue) (skipped: You are using Wifi and SSH)
 ✓  blocker
 ✓  blocker max
 ✓  blocker 4
 ✓  blocker 3
 ✓  blocker 2
 ✓  blocker 1
 ✓  blocker 0
 ✓  bluetooth off
 ✓  bluetooth pause
 ✓  bluetooth on
 ✓  bluetooth mac
 ✓  bluetooth id
 ✓  bluetooth id number
 ✓  bluetoothid
 ✓  bluetoothid number
 ✓  bootoption console
 ✓  bootoption console autologin
 ✓  bootoption desktop
 ✓  bootoption desktop autologin
 ✓  bridge (manually test w/out bats - requires reboots)
 -  burn (/dev/sdb will take a while) (skipped: No disk/usb device mounted)
 ✓  button off
 ✓  button bluetooth (check button...press any key to continue)
 ✓  camera (manually test w/out bats - requires reboots)
 -  clone (/dev/sdb will take a while) (skipped: No disk/usb device mounted)
 ✓  container
 ✓  container balena
 ✓  container none
 ✓  container docker
 ✓  coralenv (manually test w/out bats - requires coral environmental sensor board)
 ✓  services couchdb info
 ✓  services couchdb install
 ✓  services couchdb up
 ✓  services couchdb restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services couchdb port
 ✓  services couchdb ps
 ✓  services couchdb url both
 ✓  services couchdb autorun
 ✓  services couchdb autorun true
 ✓  services couchdb stop
 ✓  services couchdb down
 ✓  services couchdb cleanup
 ✓  cron tor
 ✓  cron timestamp
 ✓  cron 0W
 ✓  cron list
 ✓  default
 ✓  default network
 ✓  default tunnel
 ✓  default notice
 ✓  detect
 ✓  detectrpi
 ✓  detectrpi model
 ✓  discover rpi
 ✓  discover scan google.com (manually test w/out bats - takes time)
 ✓  discover scan scanme.nmap.org (manually test w/out bats - takes time)
 ✓  discover interface
 ✓  discover ping google.com
 ✓  discover ports localhost
 ✓  discover mac b8:29:eb:9f:42:8b
 ✓  ethernet (manually test w/out bats - may cause disconnect)
 ✓  expandfs
 ✓  feedback
 ✓  help
 ✓  help apchannel
 ✓  help aphidden
 ✓  help ap
 ✓  help blocker
 ✓  help bluetoothid
 ✓  help bluetooth
 ✓  help bootoption
 ✓  help bridge
 ✓  help burn
 ✓  help button
 ✓  help camera
 ✓  help clone
 ✓  help container
 ✓  help coralenv
 ✓  help cron
 ✓  help default
 ✓  help detectrpi
 ✓  help detect
 ✓  help discover
 ✓  help ethernet
 ✓  help expandfs
 ✓  help feedback
 ✓  help image
 ✓  help internet
 ✓  help led
 ✓  help locale
 ✓  help log
 ✓  help memory
 ✓  help networkmode
 ✓  help ntp
 ✓  help openvpn
 ✓  help password
 ✓  help rebootneeded
 ✓  help reboots
 ✓  help remote
 ✓  help rename
 ✓  help restore
 ✓  help rtc
 ✓  help sdbench
 ✓  help services
 ✓  help speedtest
 ✓  help sshkey
 ✓  help ssh
 ✓  help sshtunnel
 ✓  help staticwifi
 ✓  help temperature
 ✓  help timezone
 ✓  help tor
 ✓  help upgrade
 ✓  help usb
 ✓  help verbose
 ✓  help version
 ✓  help vnc
 ✓  help wificountry
 ✓  help wifihidden
 ✓  help wifi
 ✓  help wifistatus
 ✓  image
 ✓  internet
 ✓  services kolibri info
 ✓  services kolibri install
 ✓  services kolibri up
 ✓  services kolibri restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services kolibri port
 ✓  services kolibri ps
 ✓  services kolibri url both
 ✓  services kolibri autorun
 ✓  services kolibri autorun true
 ✓  services kolibri stop
 ✓  services kolibri down
 ✓  services kolibri cleanup
 ✓  led green heartbeat
 ✓  led red default-on
 ✓  led
 ✓  led red
 ✓  led dance
 ✓  led thanksgiving
 ✓  led christmas
 ✓  led lunarnewyear
 ✓  led valentine
 ✓  led carnival
 ✓  led onam
 ✓  locale en_US
 ✓  log
 ✓  log max
 ✓  log 4
 ✓  log 3
 ✓  log 2
 ✓  log 1
 ✓  log 0
 ✓  log show
 ✓  log show 5
 ✓  services mariadb info
 ✓  services mariadb install
 ✓  services mariadb up
 ✓  services mariadb restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services mariadb port
 ✓  services mariadb ps
 ✓  services mariadb url both
 ✓  services mariadb autorun
 ✓  services mariadb autorun true
 ✓  services mariadb stop
 ✓  services mariadb down
 ✓  services mariadb cleanup
 ✓  services mastodon info
 ✓  services mastodon install
 ✓  services mastodon up
 ✓  services mastodon restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services mastodon port
 ✓  services mastodon ps
 ✓  services mastodon url both
 ✓  services mastodon autorun
 ✓  services mastodon autorun true
 ✓  services mastodon stop
 ✓  services mastodon down
 ✓  services mastodon cleanup
 ✓  memory
 ✓  memory -g
 ✓  memory total
 ✓  memory used
 ✓  memory free -m
 ✓  services moodle info
 ✓  services moodle install
 ✓  services moodle up
 ✓  services moodle restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services moodle port
 ✓  services moodle ps
 ✓  services moodle url both
 ✓  services moodle autorun
 ✓  services moodle autorun true
 ✓  services moodle stop
 ✓  services moodle down
 ✓  services moodle cleanup
 ✓  services netdata info
 ✓  services netdata install
 ✓  services netdata up
 ✓  services netdata restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services netdata port
 ✓  services netdata ps
 ✓  services netdata url both
 ✓  services netdata autorun
 ✓  services netdata autorun true
 ✓  services netdata stop
 ✓  services netdata down
 ✓  services netdata cleanup
 ✓  networkmode
 ✓  networkmode info
 ✓  services nextcloud info
 ✓  services nextcloud install
 ✓  services nextcloud up
 ✓  services nextcloud restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services nextcloud port
 ✓  services nextcloud ps
 ✓  services nextcloud url both
 ✓  services nextcloud autorun
 ✓  services nextcloud autorun true
 ✓  services nextcloud stop
 ✓  services nextcloud down
 ✓  services nextcloud cleanup
 ✓  services ntopng info
 ✓  services ntopng install
 ✓  services ntopng up
 ✓  services ntopng restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services ntopng port
 ✓  services ntopng ps
 ✓  services ntopng url both
 ✓  services ntopng autorun
 ✓  services ntopng autorun true
 ✓  services ntopng stop
 ✓  services ntopng down
 ✓  services ntopng cleanup
 ✓  ntp local
 ✓  ntp internet
 ✓  openvpn (manually test w/out bats - requires ovpn config file)
 ✓  password raspberry
 ✓  services pihole info
 ✓  services pihole install
 ✓  services pihole up
 ✓  services pihole restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services pihole port
 ✓  services pihole ps
 ✓  services pihole url both
 ✓  services pihole autorun
 ✓  services pihole autorun true
 ✓  services pihole stop
 ✓  services pihole down
 ✓  services pihole cleanup
 ✓  services portainer info
 ✓  services portainer install
 ✓  services portainer up
 ✓  services portainer restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services portainer port
 ✓  services portainer ps
 ✓  services portainer url both
 ✓  services portainer autorun
 ✓  services portainer autorun true
 ✓  services portainer stop
 ✓  services portainer down
 ✓  services portainer cleanup
 ✓  services privatebin info
 ✓  services privatebin install
 ✓  services privatebin up
 ✓  services privatebin restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services privatebin port
 ✓  services privatebin ps
 ✓  services privatebin url both
 ✓  services privatebin autorun
 ✓  services privatebin autorun true
 ✓  services privatebin stop
 ✓  services privatebin down
 ✓  services privatebin cleanup
 ✓  rebootneeded
 ✓  reboots now (manually test w/out bats - requires reboots)
 ✓  reboots in (manually test w/out bats - requires reboots)
 ✓  reboots daily
 ✓  reboots weekly
 ✓  reboots monthly
 ✓  reboots cron "0 * * * *"
 ✓  remote status
 ✓  remote upgrade
 ✓  remote services available
 ✓  remote version 2060
 ✓  rename treehouses
 -  restore (/dev/sdb will take a while) (skipped: No disk/usb device mounted)
 ✓  rtc on rasclock
 ✓  rtc on ds3231
 ✓  rtc off
 ✓  services planet info
 ✓  services planet install
 ✓  services planet up
 ✓  services planet restart
 ✓  services available
 ✓  services available full
 ✓  services running
 ✓  services running full
 ✓  services installed
 ✓  services installed full
 ✓  services ports
 ✓  services planet port
 ✓  services planet ps
 ✓  services planet url both
 ✓  services planet autorun
 ✓  services planet autorun true
 ✓  services planet stop
 ✓  services planet down
 ✓  services planet cleanup
 ✓  speedtest
 ✓  speedtest -h
 ✓  ssh (manually test w/out bats - requires reboots)
 ✓  sshkey add "test"
 ✓  sshkey list
 ✓  sshkey delete "test"
 ✓  sshkey deleteall
 ✓  sshkey github adduser dogi
 ✓  sshkey github deleteuser dogi
 ✓  sshkey github addteam (manually test w/out bats - needs access token)
 ✓  sshtunnel (manually test w/out bats - requires dest address)
 ✓  staticwifi (manually test w/out bats - may need further config)
 ✓  temperature
 ✓  temperature fahrenheit
 ✓  temperature celsius
 ✓  timezone Etc/GMT-3
 ✓  tor add 22
 ✓  tor list
 ✓  tor status
 ✓  tor refresh
 ✓  tor stop
 ✓  tor delete 22
 ✓  tor start
 ✓  tor
 ✓  tor add 22
 ✓  tor notice now
 ✗  tor deleteall
   (from function `assert_success' in file /usr/lib/node_modules/bats-assert/src/assert.bash, line 113,
    in test file ./tor.bats, line 56)
     `assert_success && assert_output -p 'All ports'' failed

   -- command failed --
   status : 1
   output (2 lines):
     Error: there are no tor ports added.
     'cli.sh add [localPort]' to add a port and be able to use the service
   --

 ✗  tor destroy
   (from function `assert_success' in file /usr/lib/node_modules/bats-assert/src/assert.bash, line 113,
    in test file ./tor.bats, line 61)
     `assert_success && assert_output -p 'Success'' failed

   -- command failed --
   status : 1
   output (2 lines):
     Error: there are no tor ports added.
     'cli.sh add [localPort]' to add a port and be able to use the service
   --

 ✓  upgrade 1.14.0
 ✓  upgrade --check
 ✓  upgrade -f
 ✓  upgrade
 ✓  usb (manually test w/out bats - sometimes hangs)
 ✓  verbose
 ✓  verbose on
 ✓  verbose off
 ✓  version
 ✓  vnc
 ✓  vnc off
 ✓  vnc on
 ✓  vnc info
 -  wifi YOUR-WIFI-NAME (skipped: Wifi pass is present in test-cli.sh)
 -  wifi YOUR-WIFI-NAME YOUR-WIFI-PASS (skipped: No wifi settings set in test-cli.sh)
 ✓  wificountry US
 ✓  wificountry
 -  wifihidden YOUR-WIFI-NAME (skipped: Wifi pass is present in test-cli.sh)
 -  wifihidden YOUR-WIFI-NAME YOUR-WIFI-PASS (skipped: No wifi settings set in test-cli.sh)
 ✓  wifistatus

447 tests, 2 failures, 19 skipped

```
Would probably add some new commands not in the script yet like:
```
treehouses services planet icon
seafile, etc
```

**Comment by LordJashin32** [comment]
rebased branch on new master

**Comment by LordJashin32** [comment]
Tested:
```
root@treehouses:/home/pi/cli# ./cli.sh remote commands
treehouses ap local
treehouses ap internet
treehouses apchannel
treehouses aphidden local
treehouses aphidden internet
treehouses blocker
treehouses blocker max
treehouses blocker 4
treehouses blocker 3
treehouses blocker 2
treehouses blocker 1
treehouses blocker 0
treehouses bluetooth off
treehouses bluetooth pause
treehouses bluetooth on
treehouses bluetooth mac
treehouses bluetooth id
treehouses bluetooth id number
treehouses bluetoothid
treehouses bluetoothid number
treehouses bootoption console
treehouses bootoption console autologin
treehouses bootoption desktop
treehouses bootoption desktop autologin
treehouses bridge
treehouses burn
treehouses button off
treehouses button bluetooth
treehouses camera
treehouses clone
treehouses container
treehouses container balena
treehouses container none
treehouses container docker
treehouses coralenv
treehouses services couchdb info
treehouses services couchdb install
treehouses services couchdb up
treehouses services couchdb restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services couchdb port
treehouses services couchdb ps
treehouses services couchdb url both
treehouses services couchdb autorun
treehouses services couchdb autorun true
treehouses services couchdb stop
treehouses services couchdb down
treehouses services couchdb cleanup
treehouses cron tor
treehouses cron timestamp
treehouses cron 0W
treehouses cron list
treehouses default
treehouses default network
treehouses default tunnel
treehouses default notice
treehouses detect
treehouses detectrpi
treehouses detectrpi model
treehouses discover rpi
treehouses discover scan google.com
treehouses discover scan scanme.nmap.org
treehouses discover interface
treehouses discover ping google.com
treehouses discover ports localhost
treehouses discover mac b8:29:eb:9f:42:8b
treehouses ethernet
treehouses expandfs
treehouses feedback
treehouses help
treehouses help apchannel
treehouses help aphidden
treehouses help ap
treehouses help blocker
treehouses help bluetoothid
treehouses help bluetooth
treehouses help bootoption
treehouses help bridge
treehouses help burn
treehouses help button
treehouses help camera
treehouses help clone
treehouses help container
treehouses help coralenv
treehouses help cron
treehouses help default
treehouses help detectrpi
treehouses help detect
treehouses help discover
treehouses help ethernet
treehouses help expandfs
treehouses help feedback
treehouses help image
treehouses help internet
treehouses help led
treehouses help locale
treehouses help log
treehouses help memory
treehouses help networkmode
treehouses help ntp
treehouses help openvpn
treehouses help password
treehouses help rebootneeded
treehouses help reboots
treehouses help remote
treehouses help rename
treehouses help restore
treehouses help rtc
treehouses help sdbench
treehouses help services
treehouses help speedtest
treehouses help sshkey
treehouses help ssh
treehouses help sshtunnel
treehouses help staticwifi
treehouses help temperature
treehouses help timezone
treehouses help tor
treehouses help upgrade
treehouses help usb
treehouses help verbose
treehouses help version
treehouses help vnc
treehouses help wificountry
treehouses help wifihidden
treehouses help wifi
treehouses help wifistatus
treehouses image
treehouses internet
treehouses services kolibri info
treehouses services kolibri install
treehouses services kolibri up
treehouses services kolibri restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services kolibri port
treehouses services kolibri ps
treehouses services kolibri url both
treehouses services kolibri autorun
treehouses services kolibri autorun true
treehouses services kolibri stop
treehouses services kolibri down
treehouses services kolibri cleanup
treehouses led green heartbeat
treehouses led red default-on
treehouses led
treehouses led red
treehouses led dance
treehouses led thanksgiving
treehouses led christmas
treehouses led lunarnewyear
treehouses led valentine
treehouses led carnival
treehouses led onam
treehouses locale en_US
treehouses log
treehouses log max
treehouses log 4
treehouses log 3
treehouses log 2
treehouses log 1
treehouses log 0
treehouses log show
treehouses log show 5
treehouses services mariadb info
treehouses services mariadb install
treehouses services mariadb up
treehouses services mariadb restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services mariadb port
treehouses services mariadb ps
treehouses services mariadb url both
treehouses services mariadb autorun
treehouses services mariadb autorun true
treehouses services mariadb stop
treehouses services mariadb down
treehouses services mariadb cleanup
treehouses services mastodon info
treehouses services mastodon install
treehouses services mastodon up
treehouses services mastodon restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services mastodon port
treehouses services mastodon ps
treehouses services mastodon url both
treehouses services mastodon autorun
treehouses services mastodon autorun true
treehouses services mastodon stop
treehouses services mastodon down
treehouses services mastodon cleanup
treehouses memory
treehouses memory -g
treehouses memory total
treehouses memory used
treehouses memory free -m
treehouses services moodle info
treehouses services moodle install
treehouses services moodle up
treehouses services moodle restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services moodle port
treehouses services moodle ps
treehouses services moodle url both
treehouses services moodle autorun
treehouses services moodle autorun true
treehouses services moodle stop
treehouses services moodle down
treehouses services moodle cleanup
treehouses services netdata info
treehouses services netdata install
treehouses services netdata up
treehouses services netdata restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services netdata port
treehouses services netdata ps
treehouses services netdata url both
treehouses services netdata autorun
treehouses services netdata autorun true
treehouses services netdata stop
treehouses services netdata down
treehouses services netdata cleanup
treehouses networkmode
treehouses networkmode info
treehouses services nextcloud info
treehouses services nextcloud install
treehouses services nextcloud up
treehouses services nextcloud restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services nextcloud port
treehouses services nextcloud ps
treehouses services nextcloud url both
treehouses services nextcloud autorun
treehouses services nextcloud autorun true
treehouses services nextcloud stop
treehouses services nextcloud down
treehouses services nextcloud cleanup
treehouses services ntopng info
treehouses services ntopng install
treehouses services ntopng up
treehouses services ntopng restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services ntopng port
treehouses services ntopng ps
treehouses services ntopng url both
treehouses services ntopng autorun
treehouses services ntopng autorun true
treehouses services ntopng stop
treehouses services ntopng down
treehouses services ntopng cleanup
treehouses ntp local
treehouses ntp internet
treehouses openvpn
treehouses password
treehouses services pihole info
treehouses services pihole install
treehouses services pihole up
treehouses services pihole restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services pihole port
treehouses services pihole ps
treehouses services pihole url both
treehouses services pihole autorun
treehouses services pihole autorun true
treehouses services pihole stop
treehouses services pihole down
treehouses services pihole cleanup
treehouses services portainer info
treehouses services portainer install
treehouses services portainer up
treehouses services portainer restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services portainer port
treehouses services portainer ps
treehouses services portainer url both
treehouses services portainer autorun
treehouses services portainer autorun true
treehouses services portainer stop
treehouses services portainer down
treehouses services portainer cleanup
treehouses services privatebin info
treehouses services privatebin install
treehouses services privatebin up
treehouses services privatebin restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services privatebin port
treehouses services privatebin ps
treehouses services privatebin url both
treehouses services privatebin autorun
treehouses services privatebin autorun true
treehouses services privatebin stop
treehouses services privatebin down
treehouses services privatebin cleanup
treehouses rebootneeded
treehouses reboots now
treehouses reboots in
treehouses reboots daily
treehouses reboots weekly
treehouses reboots monthly
treehouses reboots cron
treehouses remote status
treehouses remote upgrade
treehouses remote services available
treehouses remote version
treehouses rename treehouses
treehouses restore
treehouses rtc on rasclock
treehouses rtc on ds3231
treehouses rtc off
treehouses services planet info
treehouses services planet install
treehouses services planet up
treehouses services planet restart
treehouses services available
treehouses services available full
treehouses services running
treehouses services running full
treehouses services installed
treehouses services installed full
treehouses services ports
treehouses services planet port
treehouses services planet ps
treehouses services planet url both
treehouses services planet autorun
treehouses services planet autorun true
treehouses services planet stop
treehouses services planet down
treehouses services planet cleanup
treehouses speedtest
treehouses speedtest -h
treehouses ssh
treehouses sshkey add
treehouses sshkey list
treehouses sshkey delete
treehouses sshkey deleteall
treehouses sshkey github adduser
treehouses sshkey github deleteuser
treehouses sshkey github addteam
treehouses sshtunnel
treehouses staticwifi
treehouses temperature
treehouses temperature fahrenheit
treehouses temperature celsius
treehouses timezone
treehouses tor add
treehouses tor list
treehouses tor status
treehouses tor refresh
treehouses tor stop
treehouses tor delete
treehouses tor start
treehouses tor
treehouses tor add
treehouses tor notice now
treehouses tor deleteall
treehouses -treehouses tor destroy
treehouses -treehouses upgrade
treehouses upgrade --check
treehouses upgrade -f
treehouses upgrade
treehouses usb
treehouses usb on
treehouses usb off
treehouses verbose
treehouses verbose on
treehouses verbose off
treehouses version
treehouses vnc
treehouses vnc off
treehouses vnc on
treehouses vnc info
treehouses wifi
treehouses wificountry
treehouses wifihidden
treehouses wifistatus
root@treehouses:/home/pi/cli#

```

**Comment by kjong** [comment]
Nice update.

There are a few commands here and there that are missing / incorrect.
Might have to just go through them manually and fix the list.

Hopefully a one time thing.

**Pull request merged**
