### PR TITLE
treehouses detectrpi for rogue RPI (fixes #733)

### LINKED ISSUE #733: need way to handle new revision codes coming in
If a ```c03113``` or some new revision code comes out for RPi4B or etc when RPi5 comes out one day. Maybe we should just check the file for a general string like RPi instead of exact model numbers to determine if the user is using a Pi. 3 of the interns in the past month or so had problems with this when c03112 or whatever wasn't in the source code.

### PR DESCRIPTION
**Pull request by LordJashin32**
- "RPI" new model introduced to account for new Pi's that may not be registered in the models array but are still showing up as a Pi logically. 
- Uses new /sys method to query whether or not it's a Raspberry Pi
- /sys/firmware/devicetree/base/model contains Raspberry Pi 4 Model B Rev 1.2 or etc. for other Pi's.

### CODE REVIEW

**Comment by dogi** [comment]
testplan:
- [ ] rpi0W
- [ ] rpi3b
- [ ] rpi3b+
- [ ] rpi4b 1GB
- [ ] rpi4b 2GB
- [ ] rpi4b 4GB

**Comment by dogi** [comment]
comment out your rpi model to make them `rogue`

**Comment by vmnet8** [comment]
```
root@lilyxxx0w:~/cli# ./cli.sh detectrpi
RPIZW
root@lilyxxx0w:~/cli# ./cli.sh detectrpi model
9000c1
```
it works well on rpi0w

**Comment by vmnet8** [comment]
```
root@lilyxxx0w:~/cli# sudo ./cli.sh detectrpi
nonrpi
root@lilyxxx0w:~/cli# sudo ./cli.sh detectrpi model
nonrpi
root@lilyxxx0w:~/cli# git diff
diff --git a/modules/detectrpi.sh b/modules/detectrpi.sh
index cfafa1f..e1ac7b3 100644
--- a/modules/detectrpi.sh
+++ b/modules/detectrpi.sh
@@ -28,7 +28,7 @@ function detectrpi {
   rpimodels["900092"]="RPIZ"
   rpimodels["900093"]="RPIZ"
   rpimodels["920093"]="RPIZ"
-  rpimodels["9000c1"]="RPIZW"
+#  rpimodels["9000c1"]="RPIZW"
   rpimodels["a02082"]="RPI3B"
   rpimodels["a020a0"]="CM3"
   rpimodels["a22082"]="RPI3B"
```

**Comment by LordJashin32** [comment]
```
Switched to a new branch 'rogue-pi'
root@r123rpi0:~/cli# git pull

warning: redirecting to https://github.com/treehouses/cli/
Already up to date.
root@r123rpi0:~/cli# 
root@r123rpi0:~/cli# cd modules
root@r123rpi0:~/cli/modules# sudo vim detectrpi.sh
root@r123rpi0:~/cli/modules# sudo treehouses detectrpi
RPIZW
root@r123rpi0:~/cli/modules# sudo vim detectrpi.sh
root@r123rpi0:~/cli/modules# cd ..
root@r123rpi0:~/cli# ./cli.sh detectrpi
RPI
root@r123rpi0:~/cli# sudo ./cli.sh detectrpi
RPI
root@r123rpi0:~/cli# 

```

**Comment by dogi** [comment]
> ```
> root@lilyxxx0w:~/cli# sudo ./cli.sh detectrpi
> nonrpi
> root@lilyxxx0w:~/cli# sudo ./cli.sh detectrpi model
> nonrpi
> root@lilyxxx0w:~/cli# git diff
> diff --git a/modules/detectrpi.sh b/modules/detectrpi.sh
> index cfafa1f..e1ac7b3 100644
> --- a/modules/detectrpi.sh
> +++ b/modules/detectrpi.sh
> @@ -28,7 +28,7 @@ function detectrpi {
>    rpimodels["900092"]="RPIZ"
>    rpimodels["900093"]="RPIZ"
>    rpimodels["920093"]="RPIZ"
> -  rpimodels["9000c1"]="RPIZW"
> +#  rpimodels["9000c1"]="RPIZW"
>    rpimodels["a02082"]="RPI3B"
>    rpimodels["a020a0"]="CM3"
>    rpimodels["a22082"]="RPI3B"
> ```

@vmnet8 think we forgot to checkout the branch ...

**Pull request merged**
