### PR TITLE
treehouses bluetooth (fixes #865)

### LINKED ISSUE #865: treehouses bluetooth is an invalid action
think we should check there if status is on or off

### PR DESCRIPTION
**Pull request by kjong**
Fixes #865

```
root@kjong:~/cli# service bluetooth start
root@kjong:~/cli# ./cli.sh bluetooth
on
root@kjong:~/cli# service bluetooth stop
root@kjong:~/cli# ./cli.sh bluetooth
off
```

### CODE REVIEW

**Comment by LordJashin32** [comment]
https://github.com/treehouses/cli/blob/master/cli.sh#L139
Already has checkroot. So user is going to be using sudo or root.
So no need for it. Took it out.

**Comment by dogi** [comment]
```
root@r125rpi4:~/cli# ./cli.sh bluetooth
on
root@r125rpi4:~/cli# treehouses bluetooth
Error: only 'on', 'off', 'pause' options are supported
root@r125rpi4:~/cli# ./cli.sh bluetooth pause
Success: the bluetooth service has been switched to default, and the service has been stopped.
root@r125rpi4:~/cli# ./cli.sh bluetooth
on
root@r125rpi4:~/cli# ./cli.sh bluetooth off
Success: the bluetooth service has been switched to default, and the service has been stopped.
root@r125rpi4:~/cli# ./cli.sh bluetooth
Warning: The unit file, source configuration file or drop-ins of bluetooth.service changed on disk. Run 'systemctl daemon-reload' to reload units.
on
root@r125rpi4:~/cli# systemctl daemon-reload
root@r125rpi4:~/cli# ./cli.sh bluetooth
on
root@r125rpi4:~/cli# ./cli.sh bluetooth off
Success: the bluetooth service has been switched to default, and the service has been stopped.
root@r125rpi4:~/cli# ./cli.sh bluetooth
Warning: The unit file, source configuration file or drop-ins of bluetooth.service changed on disk. Run 'systemctl daemon-reload' to reload units.
on
```

**Comment by dogi** [comment]
@kjong as you see above there is more to be done

**Comment by kjong** [comment]
```
root@kjong:~/cli# ./cli.sh bluetooth on
Success: the bluetooth service has been started.
root@kjong:~/cli# ./cli.sh bluetooth
on
root@kjong:~/cli# ./cli.sh bluetooth pause
Success: the bluetooth service has been switched to default, and the service has been stopped.
root@kjong:~/cli# ./cli.sh bluetooth
off
root@kjong:~/cli# ./cli.sh bluetooth off
Success: the bluetooth service has been switched to default, and the service has been stopped.
root@kjong:~/cli# ./cli.sh bluetooth
off
root@kjong:~/cli# ./cli.sh bluetooth on
Success: the bluetooth service has been started.
root@kjong:~/cli# ./cli.sh bluetooth
on
```

**Pull request merged**
