### PR TITLE
`treehouses wifi` & `wifihidden` enterprise (fixes #431)

### LINKED ISSUE #431: How to connect to WPA2/PEAP/MSCHAPv2 enterprise wifi networks
Need to find a proper solution to  connect rp4 to enterprise wifi networks.
FYI:
> in ubuntu base, This following article mentions where they contain for the rp4  [How to connect to WPA2/PEAP/MSCHAPv2 enterprise wifi networks](https://askubuntu.com/questions/279762/how-to-connect-to-wpa2-peap-mschapv2-enterprise-wifi-networks-that-dont-use-a-c#295600).
> This [network manager](https://raspberrypi.stackexchange.com/questions/29783/how-to-setup-network-manager-on-raspbian) utility support WPA2/PEAP/MSCHAPv2 enterprise wifi networks.

### PR DESCRIPTION
**Pull request by LordJashin32**
- [x] - WPA-EAP support confirmed working with pfsense qotom j1900
- [x] - Works without certificate
- [x] - Extends codebase instead of rewriting it
- [x] - uses older "wext" driver
Might need testing on older Pi's. Other than that. Should be good to go. 

https://gist.github.com/elec3647/1e223c02ef2a9a3f836db7984011b53b

### CODE REVIEW

**Comment by LordJashin32** [comment]
@saura8h , I assume when you ran the upgrade commands your Raspberry Pi was connected to a network? Did you try multiple times? Your Pi will need internet in order to get this branch onto it. If there's still an issue. I would just skip that and clone this branch directly using your knowledge on git. And then run `./cli.sh wifi <ESSID> [password] [identity]`

**Comment by LordJashin32** [comment]
The Android app, don't be heavily reliant on the buttons/interfaces on there. We are working through some bugs on that currently so happens. Anyway. The Terminal part of the Android App is what you should use so we can understand what's happening. 

`treehouses default / default network` commands return the Raspberry Pi to an Ethernet Cable mode. NO WIFI. This is important to remember. So if you are trying to connect to it over SSH it isn't going to work if you don't have an ethernet cord plugged in, and have the ip address for it. 

`treehouses networkmode info` This command prints out whatever ip address is available. If its set to default network. You'll get the eth0 or ethernet AKA ethernet port IP address. If you have ran `treehouses wifi` and got success. Then it will be a wlan0, and an ip address. 

In order for you to connect to your RPi over SSH. Your RPi has to be connected to the same internet that your personal or phone or device is connected to. so that they are on the same LAN (local area network). Whenever your devices connects to internet/mobile hotspot/whatever. The mobile hotspot/internet will assign an ip address to that device. So then other devices on the network can access it. This is called the DHCP server. The RPi has one as well that we use sometimes in `treehouses ap`

**Comment by LordJashin32** [comment]
@law-lin there was no changes to the passwordless version of wifi. What settings did you set on your NETGEAR75? The Wifi code only supports security with NONE or WPA-PSK. So if you didn't set it to NONE for SSID security when you tried it. Then it wouldn't work. And empty password of course for the SSID.

**Comment by law-lin** [comment]
@LordJashin32 I have WPA2-PSK security enabled. I do have a password for NETGEAR75, but can this disconnection be avoided if the user doesn't enter a password?

**Comment by LordJashin32** [comment]
> @LordJashin32 I have WPA2-PSK security enabled. I do have a password for NETGEAR75, but can this disconnection be avoided if the user doesn't enter a password?

Theoretically yes but its not programmed into the code to do that yet. This is very bare bones basic. I didn't even create this code. Its been here since a while. This isn't a best case code but a solution to a problem a couple users had with college wifi. If you can set your wifi to WPA Enterprise security. And try connecting normally with this. I'd love to see what happens with your Pi.

**Comment by law-lin** [comment]
@LordJashin32 I set my wifi to WPA Enterprise and connected normally - it was successful.

```
root@treehouses:~/cli# ./cli.sh wifi NETGEAR75 *********
connected to password network; our wifi ip: 192.168.1.15

```

**Comment by LordJashin32** [comment]
> @LordJashin32 I set my wifi to WPA Enterprise and connected normally - it was successful.
> 
> ```
> root@treehouses:~/cli# ./cli.sh wifi NETGEAR75 *********
> connected to password network; our wifi ip: 192.168.1.15
> ```

Nice. Do you by any chance have WPA Enterprise 2 as well? Cheers. Thanks for the test.

**Comment by LordJashin32** [comment]
It seems this was all caused by an upstream issue. See https://github.com/treehouses/cli/issues/1394 . 
Going to update this PR to use "wext" driver. Should fix all issues.

**Comment by LordJashin32** [comment]
Okay I pushed the fixes. Cheers.

**Comment by LordJashin32** [comment]
> Works for me. But I was needed to add one line in wpa_supplicant.conf
> 
> ```
> phase1="peaplabel=0"
> ```

Nice. Okay. added that line to it.

**Comment by dogi** [comment]
all please test if normal wifi stuff (open and wpa2) is still working

**Comment by LordJashin32** [comment]
Can't test wifi without an ESSID and Password. So those tests are working fine. You just have to provide that. There's no way to write the tests another way without bats complaining. This is separate issue. Please check **https://github.com/treehouses/cli/blob/master/tests/README.md**
**https://github.com/treehouses/cli/blob/master/tests/wifi.bats**

**Pull request merged**
