### PR TITLE
treehouses tunnels command

### PR DESCRIPTION
**Pull request by LordJashin32**
- treehouses tunnels info
- treehouses tunnels pagekite
```bash
pi@treehouses:~/cli $ ./cli.sh tunnels
Error: unknown command
pi@treehouses:~/cli $ ./cli.sh tunnels info
https://github.com/pagekite/PyPagekite

PageKite is a reverse proxy tool that connects local servers to the public Internet.
It gives proper domain names to servers running on localhost and makes them visible to the world, bypassing NAT and firewalls.
The pagekite.py and libpagekite source code is licensed under
version 3.0 of the GNU Affero General Public License as published by the Free Software Foundation.
We also offer sponsored accounts to Free Software projects which fulfill certain criteria.
https://pagekite.net/support/free-for-foss
pi@treehouses:~/cli $ ./cli.sh tunnels pagekite
>>> Hello! This is pagekite v0.5.9.3.                           [CTRL+C = Stop]
    Connecting to front-end relay 45.79.196.141:443 ...
     - Protocols: http http2 http3 https websocket irc finger httpfinger raw
     - Protocols: minecraft
     - Ports: 79 80 443 843 2222 3000 4545 5222 5223 5269 5670 6667 8000 8080
     - Ports: 8081 8082 8083 9292 25565
     - Raw ports: virtual
    Quota: You have 2555.45 MB, 31 days and 5 connections left.
~<> Flying localhost:80 as https://tristan32.pagekite.me/
^C< pagekite.py [flying]   Only connected to 1/2 front-end relays, will retry..
pi@treehouses:~/cli $                                                                                                                             
```

### CODE REVIEW

**Comment by jamjakpa** [comment]
image

I have tested it on my RPI 4 all looks good !

**Comment by phamduchongan93** [comment]
You guys are amazing. I've been struggling to find the solution for this mater.

**Comment by kjong** [comment]
Is there going to be a pull request on `builder` for the package?

**Comment by LordJashin32** [comment]
> Is there going to be a pull request on `builder` for the package?

Done. Thanks for the reminder.

**Comment by LordJashin32** [comment]
Maybe I misunderstand what @dogi wants here. Are we running our own PageKite server? Or are we just using their service? And if its the latter, than it will be hard to get it to be non interactive because the need to signup for an account to pagekite.

**Comment by dogi** [comment]
> Maybe I misunderstand what @dogi wants here. Are we running our own PageKite server? Or are we just using their service? And if its the latter, than it will be hard to get it to be non interactive because the need to signup for an account to pagekite.

@LordJashin32 good question
I wwish we could build latter and after that maintain it
but so far we mostly want non-interactive cli command
of whatever service does that :)

**Comment by jayala-29** [comment]
Brainstorm
-----------
maybe something like `treehouses tunnels [<email> <sitename>]` to automate process that:
+runs the pagekite command:`pagekite 80 <email> <sitename>.pagekite.me`
+says 'Y' to user agreement
+signs up with [email]
+says 'Y' to finish sign-up process 
+maybe also auto-copy to clipboard the access link afterwards

the process of events would be printed to terminal, or just this part:
```
>>> Hello! This is pagekite v0.5.9.3.                           [CTRL+C = Stop]
    Connecting to front-end relay 173.255.248.133:443 ...                      
     - Protocols: http http2 http3 https websocket irc finger httpfinger raw   
     - Protocols: minecraft                                                    
     - Ports: 79 80 443 843 2222 3000 4545 5222 5223 5269 5670 6667 8000 8080  
     - Ports: 8081 8082 8083 9292 25565                                        
     - Raw ports: virtual                                                      
!!! Quota: You have 0.02 MB, 1 days and 5 connections left.                    
~<> Flying localhost:80 as https://rand.pagekite.me/   
``` 

the user would then have to:
(option 1)
1.  verify their email to keep their account active (optional?)
2.  open their browser and paste the link
OR
(option 2)
do nothing, their browser opens up with the link created to display Planet Learning page

**Comment by jayala-29** [comment]
this seems to be working thus far, not letting me test properly though since it detects I'm trying to create multiple accounts from the same computer:
`printf "Y\n$(email)\$(sitename)\n" | /usr/local/bin/pagekite.py --signup'

**Comment by jayala-29** [comment]
I'm gonna need others to test the above comment since I've maxed out my pagekite signups

**Comment by dogi** [comment]
https://github.com/treehouses/cli/pull/1200

**Pull request closed without merging**
