### PR TITLE
treehouses led both (fixes #521)

### LINKED ISSUE #521: treehouses led both
both = dealing with red and green at the same time

### PR DESCRIPTION
**Pull request by pattanawadee88**

### CODE REVIEW

**Comment by kjong** [comment]
> Everything looks good, my only suggestion would be to find a way to label each led output when running 'treehouses led both' to view the current mode of each led. Perhaps this could be accomplished by modifying the if statement beginning at line 28?

Super quick and dirty way I did this was:
```
elif [ "$color" = "both" ]; then
  echo "green:"
  led green $trigger
  echo "red:"
  led red $trigger
  exit 0
```

Sample output:
```
root@kjong:~/cli# ./cli.sh led both
green:
default-on
red:
heartbeat
```

**Comment by pattanawadee88** [comment]
```
root@pattanawadee88:~/cli# ./cli.sh led both heartbeat
green led: 
green led: heartbeat
red led: 
red led: heartbeat
```

**Comment by kjong** [comment]
Sample output

Screenshot 2019-11-25 12 10 47

**Comment by pattanawadee88** [comment]
```
root@pattanawadee88:~/cli# ./cli.sh led both
green led: heartbeat
red led: default-on
root@pattanawadee88:~/cli# ./cli.sh led bothnone
Error: led 'bothnone' is not present
root@pattanawadee88:~/cli# ./cli.sh led both none
green led: none
red led: none
root@pattanawadee88:~/cli# ./cli.sh led both
green led: none
red led: none
root@pattanawadee88:~/cli# ./cli.sh led both heartbeat
green led: heartbeat
red led: heartbeat
```

**Pull request merged**
