### PR TITLE
Update cli.sh

### PR DESCRIPTION
**Pull request by rhuturajm**
sshkeyadd help more info

### CODE REVIEW

**Comment by i5o** [comment]
Hi @rhuturajm, good start.
What you have done looks good, except for the part that you are replacing the help of **rename**, this means that you need to add your stuff after **rename**

```
rename)
 ... do stuff ...
 ;;
sshkeyadd)
 ... your stuff ..
 ;;
```

please ask if you have any question

**Comment by rhuturajm** [comment]
@i5o Hey do you mean to say the structure would be something like this:
image

**Comment by i5o** [comment]
Exactly like that @rhuturajm

**Comment by rhuturajm** [comment]
@i5o I had discussion regarding this with dogi and we decided on creating separate pull request for each help command info

**Comment by i5o** [comment]
@rhuturajm lets discuss this on wednesday hacking meeting

**Pull request closed without merging**
