### PR TITLE
treehouses log (fixes #599)

### LINKED ISSUE #599: treehouses log 0|1|2?
`echo "$*" >> /var/log/treehouses.log` in `cli.sh`

### PR DESCRIPTION
**Pull request by LordJashin32**
- added log.sh
- added config.sh
- updated readme/help/tab completion
- added log command 
- added internal logging functions 
- added variable $BASENAME
- added removal of config file on uninstall
- moved variables in globals.sh to config.sh
- tested on RPi4

Testing for others: 
```
git clone http://github.com/treehouses/cli
cd cli
git checkout lord_logger
sudo ./cli.sh log 1
sudo cat /etc/treehouses.conf
sudo npm install --unsafe-perm -g ./
sudo cat /etc/treehouses.conf
Should be gone ^
sudo ./cli.sh image
sudo ./cli.sh log show
sudo ./cli.sh log show 1
sudo ./cli.sh log 2
sudo ./cli.sh log 3
sudo ./cli.sh log 4
sudo ./cli.sh log
sudo ./cli.sh log max
sudo ./cli.sh image
sudo ./cli.sh log 0
sudo ./cli.sh log show 20
log max turns on bash tracing with bash -x
You should see tons of output showing
you the sequence of commands executed
sudo ./cli.sh image
everything should look back to normal on output
```
Notes to self:
Can add an alias to make 'log max' strictly log only to file but output to screen look normal
Right now it seems more useful to developer/user to dump onto screen and log to see what
is going on.

### CODE REVIEW

**Comment by LordJashin32** [comment]
Filename example: 2020-01-21.log
Inside the log: 
`
22:57:45-INFO-cli.sh: execution started with 'image' arguments
22:57:47-INFO-cli.sh: execution started with 'version' arguments
22:59:52-INFO-cli.sh: execution started with 'sshkey list' arguments
`

**Comment by LordJashin32** [comment]
In order to test this run 
```
sudo npm install --unsafe-perm -g yourtreehousesclidirectory
./cli.sh log 1
./cli.sh log 0
./cli.sh image
sudo nano /etc/treehouses.conf
sudo nano /var/log/syslog ; page down/scroll down to bottom
```

**Comment by LordJashin32** [comment]
This was one heck of a journey. Note to self: system to test on pi without using git commits. Or perhaps alias to make amend commit faster.

**Comment by vmnet8** [comment]
it works well
```
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log 1
Log 1: level set to Info
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log 2
Log 2: level set to Info and Warning
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log 3
Log 3: level set to Info, Warning, and Error
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log 4
Log 4: level set to Info, Warning, Error, and Debug
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log show
Jan 29 19:21:55 vmnet8 @treehouses/cli: Log 2: level set to Info and Warning
Jan 29 19:22:00 vmnet8 @treehouses/cli: log 3
Jan 29 19:22:00 vmnet8 @treehouses/cli: Log 3: level set to Info, Warning, and Error
Jan 29 19:22:03 vmnet8 @treehouses/cli: log 4
Jan 29 19:22:03 vmnet8 @treehouses/cli: Log 4: level set to Info, Warning, Error, and Debug
Jan 29 19:22:08 vmnet8 @treehouses/cli: log show
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log show 5
Jan 29 19:22:00 vmnet8 @treehouses/cli: Log 3: level set to Info, Warning, and Error
Jan 29 19:22:03 vmnet8 @treehouses/cli: log 4
Jan 29 19:22:03 vmnet8 @treehouses/cli: Log 4: level set to Info, Warning, Error, and Debug
Jan 29 19:22:08 vmnet8 @treehouses/cli: log show
Jan 29 19:22:14 vmnet8 @treehouses/cli: log show 5
root@vmnet8:/home/ubuntu/git_repo/cli# ./cli.sh log max
Log X: level set to max

```

**Pull request merged**
