### PR TITLE
treehouses reboots (fixes #443)

### LINKED ISSUE #443: treehouses reboot now|in|cron|daily|weekly|monthly

### PR DESCRIPTION
**Pull request by CalebProvost**
```
Usage: cli.sh reboots <now|in|cron|daily|weekly|monthly>

  Reboots system at selected time

  Example:
  cli.sh reboots daily
  System will reboot daily at 00:00

  cli.sh reboots in 120
  System will reboot in 120 seconds. ctrl+c to cancel.

  cli.sh reboots cron "0 * * * *"
  Rebooting with frequency of "0 * * * *" added

  Set frequency: * * * * *
                 │ │ │ │ │
                 │ │ │ │ └── day of the week    (* | #/# | 0 - 6 or Sun to Sat)
                 │ │ │ └──── month              (* | #/# | 1 - 12)
                 │ │ └────── day of the month   (* | #/# | 1 - 31)
                 │ └──────── hour               (* | #/# | 0 - 23)
                 └────────── minute             (* | #/# | 0 - 59)
```

### CODE REVIEW

**Comment by irisb1701** [comment]
don't forget to update _treehouses file,
also is there an option to reverse after selecting reboots daily/weekly/monthly?
or something to view what you have selected for a reboot status in order to change/un-do it

**Comment by CalebProvost** [comment]
> don't forget to update _treehouses file,

Done! 😄 

> also is there an option to reverse after selecting reboots daily/weekly/monthly?

Yes. Executing the command a second time will remove the task. For custom added ones I have it point to the cron command.

> or something to view what you have selected for a reboot status in order to change/un-do it

Um... No. I'll make it to where no following arguments just prompt the listed cron jobs, followed by a prompt to run "help" for more commands.

**Comment by CalebProvost** [comment]
> Is ` ./cli.sh reboots cron "0****"` this command suppose to remove the previous reboot time
> 
> ```
> root@pattanawadee88:~/cli# ./cli.sh reboots cron "0****"
> "-":4: bad command
> errors in crontab file, can't install.
> Rebooting with frequency of "0****" added
> root@pattanawadee88:~/cli# ./cli.sh reboots monthly
> Job to reboot monthly removed
> ```

You're forgetting the spaces between each asterisk ` ./cli.sh reboots cron "0 * * * *"`
Once you run it you should see what to do next if its already a task.

**Comment by pattanawadee88** [comment]
> > Is ` ./cli.sh reboots cron "0****"` this command suppose to remove the previous reboot time
> > ```
> > root@pattanawadee88:~/cli# ./cli.sh reboots cron "0****"
> > "-":4: bad command
> > errors in crontab file, can't install.
> > Rebooting with frequency of "0****" added
> > root@pattanawadee88:~/cli# ./cli.sh reboots monthly
> > Job to reboot monthly removed
> > ```
> 
> You're forgetting the spaces between each asterisk ` ./cli.sh reboots cron "0 * * * *"`
> Once you run it you should see what to do next if its already a task.

so if entering without the spaces between each asterisk, it should not remove  the previous reboot time

**Comment by CalebProvost** [comment]
> so if entering without the spaces between each asterisk, it should not remove the previous reboot time

No. The function just doesn't work. Adding or removing would require the exact input. Your execution of `./cli reboots cron` failed. To use it, it'll need spaces between the asterisks. Running it again will prompt you _how_ to remove the cron job.

**Comment by pattanawadee88** [comment]
> No. The function just doesn't work. Adding or removing would require the exact input. Your execution of `./cli reboots cron` failed. To use it, it'll need spaces between the asterisks. Running it again will prompt you _how_ to remove the cron job.

I'll test it again :)

**Comment by irisb1701** [comment]
```
root@treehouses:/home/pi/cli# ./cli.sh reboots weekly
System will reboot at 00:00 every Sunday
root@treehouses:/home/pi/cli# ./cli.sh reboots weekly
Job to reboot weekly removed
root@treehouses:/home/pi/cli# ./cli.sh reboots
No timeframe selected. For how to use "reboots" run: cli.sh help reboots

Tasks scheduled:
@daily reboot
root@treehouses:/home/pi/cli# ./cli.sh reboots daily
Job to reboot daily removed
root@treehouses:/home/pi/cli# ./cli.sh reboots
No timeframe selected. For how to use "reboots" run: cli.sh help reboots

Tasks scheduled:
root@treehouses:/home/pi/cli# 

```
removing the previous reboot task and listing of tasks works perfect, now just wondering if how to do both of these should be mentioned in the help function

**Comment by irisb1701** [comment]
```
root@treehouses:/home/pi/cli# ./cli.sh reboots cron "6 10 24 4 20" 
Reboot frequency of "6 10 24 4 20" already established
To delete it, use: cli.sh cron delete "6 10 24 4 20"
root@treehouses:/home/pi/cli# ./cli.sh cron delete "6 10 24 4 20" 
Usage: cli.sh

   help [command]                            gives you a more detailed info about the command or will output this
   expandfs                                  expands the partition of the RPI image to the maximum of the SDcard

```

looks like `./cli.sh cron delete "6 10 24 4 20"` doesnt work if I did it correctly 
 
also, I entered 6 for the day (saturday) 10 for the month, and 24 for the day, which should be Thursday. Looks like we technically don't need day of the week for cron cause it can conflict with the actual day selected?

**Pull request merged**
