### PR TITLE
treehouses services netdata (fixes #671)

### LINKED ISSUE #671: treehouses services netdata

### PR DESCRIPTION
**Pull request by vmnet8**
under /template/service, add netdata subdir

add netdata_autorun and netdata_yml.sh

### CODE REVIEW

**Comment by vmnet8** [comment]
Please test:
1.switch to netdata branch, under  ```cli/templates/services/netdata```
2.run 
```./netdata_yml.sh```
3.run 
```docker-compose -f /srv/netdata/netdata.yml -p netdata up -d```
4. go to browser
```http://your ip:19999```

**Comment by phamduchongan93** [comment]
@vmnet8 what are the expected output?

**Comment by kjong** [comment]
Looks good. Is this going to be added to services?

**Comment by vmnet8** [comment]
> @vmnet8 what are the expected outputs?
> netdata
> That is the output I have after following the step.
> Be advised, the test was done on tree houses image 120 (RPi4).

I think this is what we want. thank you for testing

**Comment by vmnet8** [comment]
> Looks good. Is this going to be added to services?

yes. 
Thanks for testing.

**Comment by phamduchongan93** [comment]
Detail of this docker app is amazing, and very appealing.

**Pull request merged**
