### PR TITLE
`treehouses shadowsocks` refactor

### PR DESCRIPTION
**Pull request by darthnoward**
#1719 #1720 #1721

### CODE REVIEW

**Comment by darthnoward** [comment]
```
root@treehouses:~# treehouses shadowsocks add { \"server\": \"sgp02.clashcloud.tech\", \"local_address\": \"127.0.0.1\", \"local_port\": 1090, \"server_port\": 58817, \"password\": \"1vgfdr\", \"method\": \"rc4-md5\" }
Config named "tmptmpIHk0sG67FC" saved.
Use `treehouses shadowsocks start tmptmpIHk0sG67FC` to start client.
```

**Comment by koxuan** [comment]
ubuntu_xJsvaYiAvk

Even though its started, I could not get the shell session going. Am I doing something wrongly?

**Comment by darthnoward** [comment]
> ubuntu_xJsvaYiAvk
> 
> Even though its started, I could not get the shell session going. Am I doing something wrongly?

what is the output of `treehouses shadowsocks list`

**Comment by darthnoward** [comment]
`treehouses config`

**Pull request merged**
