### PR TITLE
help function checkargn (fixes #697)

### LINKED ISSUE #697: no check for too many arguments
Most of the code doesn't care if a user passes endless arguments to them e.g.

### PR DESCRIPTION
**Pull request by LordJashin32**
Fixes #697
- Checks the number of arguments passed for each command throws an error if too many arguments are passed. In the event of using external commands (speedtest) no checking of how many arguments is made.

### CODE REVIEW

**Comment by LordJashin32** [comment]
To test. Just type in too many arguments for a command in treehouses.

**Comment by kjong** [comment]
```
if [ "$#" -gt 2 ]; then
  echo "Too many arguments."
  discover_help
  exit 1
fi
```

Code snippet from `discover.sh`.
Might be helpful, but it's pretty much doing the same thing as yours.

**Comment by LordJashin32** [comment]
> ```
> if [ "$#" -gt 2 ]; then
>   echo "Too many arguments."
>   discover_help
>   exit 1
> fi
> ```
> 
> Code snippet from `discover.sh`.
> Might be helpful, but it's pretty much doing the same thing as yours.

Good idea. Reworked the current code to do this behavior new behavior:
```pi@treehouses:~/cli $ ./cli.sh image sdfds
Error: Too many arguments.

Usage: cli.sh image

Returns the version of the system image which is currently running

Example:
  cli.sh image
      Prints the current version of the system image.


```

**Comment by vmnet8** [comment]
```
pi@treehouses:~/git_repo/cli $ ./cli.sh feedback
No feedback was submitted.
pi@treehouses:~/git_repo/cli $ ./cli.sh feedback kka ieii
Error: Too many arguments.

Usage: cli.sh feedback <message>

Shares feedback with the developers

Example:
  cli.sh feedback "Hi, you are very awesome"
      Gives some feedback that the developers will read :)
```

works well, good job

**Comment by kjong** [comment]
```
root@kjong:~/cli# ./cli.sh remote status
true dc:a6:32:00:fb:ae release-123 1.13.20 RPI4B
root@kjong:~/cli# ./cli.sh remote status asd
true dc:a6:32:00:fb:ae release-123 1.13.20 RPI4B
```

For modules like `remote.sh` where some functions have less required arguments than other functions in the same module, the number of arguments aren't checked correctly.

Not technically wrong, so maybe not a big issue.

To fix this you could check in every function individually, but not sure if it's worth the trouble.

**Comment by jamjakpa** [comment]
On treehouses remote app , if i type:  treehouses speedtest fffh fffk 
 command 'treehouses speedtest aahs ffjd' return nothing

**Comment by LordJashin32** [comment]
> ```
> root@kjong:~/cli# ./cli.sh remote status
> true dc:a6:32:00:fb:ae release-123 1.13.20 RPI4B
> root@kjong:~/cli# ./cli.sh remote status asd
> true dc:a6:32:00:fb:ae release-123 1.13.20 RPI4B
> ```
> 
> For modules like `remote.sh` where some functions have less required arguments than other functions in the same module, the number of arguments aren't checked correctly.
> 
> Not technically wrong, so maybe not a big issue.
> 
> To fix this you could check in every function individually, but not sure if it's worth the trouble.
> 
> ```
> root@kjong:~/cli# ./cli.sh help asd asd
> Error: Too many arguments.
> /root/cli/modules/globals.sh: line 53: help_help: command not found
> ```
> 
> Trying to run `eval "$(echo $SCRIPTARGS | cut -d' ' -f1)_help"` for `help.sh` -> tries to run `help_help` which doesn't exist.
> 
> Another minor issue but maybe worth fixing by just adding an if check.

Okay i fixed the ```help_help``` issue.

**Comment by LordJashin32** [comment]
> On treehouses remote app , if i type: treehouses speedtest fffh fffk
> command 'treehouses speedtest aahs ffjd' return nothing

That speedtest command just runs the package directly. There is no code to handle different amount of inputs. It just passes all the arguments to the command. That's why there's no use checking for too many arguments for it.

**Pull request merged**
