### PR TITLE
treehouses cron (fixes #445) (fixes #443) (fixes #442)

### LINKED ISSUE #442: treehouses cron list|add|delete|deleteall
... similar to `tor.sh` by using `crontab`

### LINKED ISSUE #443: treehouses reboot now|in|cron|daily|weekly|monthly

### LINKED ISSUE #445: looking for a way to know uptimes
... so that later we can say this rpi was on this times and not the other

wonder if there are already logfiles we can harvest

### PR DESCRIPTION
**Pull request by CalebProvost**
new feature:
`treehouses cron [list|0W|tor|timestamp|add "<job>"|delete "<word/phrase>"|deleteall]` : see below for details

* `treehouses cron list`:   Lists all cron jobs 
* `treehouses cron 0W`:   Creates a daily reboot task; Needed for RPi Zero W"
* `treehouses cron tor`:   Sends \"tor notice now\" every 72 hours"
* `treehouses cron timestamp`:   Creates /var/log/uptime.log, logging every 15 minutes
* `treehouses cron add "<job>"`:   Adds custom job to cron
* `treehouses cron delete "<job>"`:   Deletes custom job matching "word or phrase"
* `treehouses cron deleteall`:   Deletes all cron jobs

### CODE REVIEW

**Comment by CalebProvost** [comment]
> Delete is not working.

Should be working now. Thank you. 😄 

> @dogi, @CalebProvost In Examples section, it is not cli.sh cron but treehoues cron?
> Also, I got the message: "no crontab for root"
> Is this message is fine?

Are you running it as sudo?

**Comment by hiroTochigi** [comment]
> > Delete is not working.
> 
> Should be working now. Thank you. 
> 
> > @dogi, @CalebProvost In Examples section, it is not cli.sh cron but treehoues cron?
> > Also, I got the message: "no crontab for root"
> > Is this message is fine?
> 
> Are you running it as sudo?

Yes, I am running it as sudo

**Comment by CalebProvost** [comment]
> Yes, I am running it as sudo

Hm... I'm updating to the latest image and testing it myself to see what I might be missing.
 
> I can try the delete function.
> It works.
> 
> However, sorry, I have one more issue.
> image
> It seems like that add function does not work?

That's because you're using it wrong. What you want to add needs to be in quotes. `treehouses cron add "<job>"`

> Finally, I think that this is the next iteration.
> I think that this is a complicated project; especially delete function.
> For example, there are two schedules for treehouses command: [treehouses tor notice now] and [treehouses something].

What? I don't think I understand. The `treehouses tor notice now` is executed immediately through the `treehouses tor` command. This `treehouses cron` command works with the following arguments: 
```
treehouses cron [list|0W|tor|timestamp] : lists all active cron jobs [lists jobs|adds premade job or removes it if active]
```
or
```
treehouses cron [add "<*>"|delete "<*>"|deleteall] : [add custom cron job|delete custom cron job|deletes all cron jobs]
```

> [treehouses cron delete] removes two treehouses schedule? Or does not remove anything?

`treehouses cron delete "job to be deleted"` will delete any job that has the **`"word"`** or **`"phrase"`** within it (deleting the line that has it).
`treehouses cron deleteall` will reset the entire cron job list to nothing.

When you use the predefined (because they're most likely to be used) jobs like `0W` it'll add it automatically without needing to write out the syntax. Using it again will remove it without needing to write another line (just up arrow and enter).

Should I rewrite the help file to make it more understandable?

**Comment by hiroTochigi** [comment]
> > However, sorry, I have one more issue.
> > image
> > It seems like that add function does not work?
> 
> That's because you're using it wrong. What you want to add needs to be in quotes. `treehouses cron add "<job>"`

Sorry, I did not pay attention to the quote.
I think that if you add the use case of the add function in Example, it could be easier.
   
> > Finally, I think that this is the next iteration.
> > I think that this is a complicated project; especially delete function.
> > For example, there are two schedules for treehouses command: [treehouses tor notice now] and [treehouses something].
> 
> What? I don't think I understand. The `treehouses tor notice now` is executed immediately through the `treehouses tor` command. This `treehouses cron` command works with the following arguments:
> 
> ```
> treehouses cron [list|0W|tor|timestamp] : lists all active cron jobs [lists jobs|adds premade job or removes it if active]
> ```
> 
> or
> 
> ```
> treehouses cron [add "<*>"|delete "<*>"|deleteall] : [add custom cron job|delete custom cron job|deletes all cron jobs]
> ```
> 
> > [treehouses cron delete] removes two treehouses schedule? Or does not remove anything?
> 
> `treehouses cron delete "job to be deleted"` will delete any job that has the **`"word"`** or **`"phrase"`** within it (deleting the line that has it).
> `treehouses cron deleteall` will reset the entire cron job list to nothing.
> 
> When you use the predefined (because they're most likely to be used) jobs like `0W` it'll add it automatically without needing to write out the syntax. Using it again will remove it without needing to write another line (just up arrow and enter).
> 
> Should I rewrite the help file to make it more understandable?

Year, this is also my bad.
I could not test the delete function fully because I could not add jobs.
Sorry about it.

**Comment by CalebProvost** [comment]
> Sorry, I did not pay attention to the quote.
> I think that if you add the use case of the add function in Example, it could be easier.

😄 No worries, it happens. 
A good program is worthless if nobody can understand it. So my latest commit has 
```
HOW TO ADD A CRON JOB:
  Set the frequency (shown below) of when you want the job to execute followed by the command
  Example: $(basename "$0") cron add "*/15 6-8 * 3 * uname"
           This will execute "uname" at every 15th minute within the hours of 6 through 8 in March
  Frequency Method: * * * * * command-to-execute
                    │ │ │ │ │
                    │ │ │ │ └── day of the week    (* | #/# | 0 - 6 or Sun to Sat)
                    │ │ │ └──── month              (* | #/# | 1 - 12)
                    │ │ └────── day of the month   (* | #/# | 1 - 31)
                    │ └──────── hour               (* | #/# | 0 - 23)
                    └────────── minute             (* | #/# | 0 - 59)
```
Will this work or should I make changes?
Thank you!

**Comment by hiroTochigi** [comment]
> > Sorry, I did not pay attention to the quote.
> > I think that if you add the use case of the add function in Example, it could be easier.
> 
>  No worries, it happens.
> A good program is worthless if nobody can understand it. So my latest commit has
> 
> ```
> HOW TO ADD A CRON JOB:
>   Set the frequency (shown below) of when you want the job to execute followed by the command
>   Example: $(basename "$0") cron add "*/15 6-8 * 3 * uname"
>            This will execute "uname" at every 15th minute within the hours of 6 through 8 in March
>   Frequency Method: * * * * * command-to-execute
>                     │ │ │ │ │
>                     │ │ │ │ └── day of the week    (* | #/# | 0 - 6 or Sun to Sat)
>                     │ │ │ └──── month              (* | #/# | 1 - 12)
>                     │ │ └────── day of the month   (* | #/# | 1 - 31)
>                     │ └──────── hour               (* | #/# | 0 - 23)
>                     └────────── minute             (* | #/# | 0 - 59)
> ```
> 
> Will this work or should I make changes?
> Thank you!

Yes, it is great.

**Comment by kjong** [comment]
```
root@kjong:~/cli# ./cli.sh cron add "*/15 6-8 * 3 * uname"
no crontab for root
"*/15 6-8 * 3 * uname" cron job added
root@kjong:~/cli# ./cli.sh cron list
List of cron jobs:
*/15 6-8 * 3 * uname
root@kjong:~/cli# ./cli.sh cron delete "*/15 6-8 * 3 * uname"
Could not find a job containing "*/15 6-8 * 3 * uname" to delete
root@kjong:~/cli# ./cli.sh cron list
List of cron jobs:
*/15 6-8 * 3 * uname

**Pull request merged**
