### PR TITLE
treehouses fidget spinner (fixes #719)

### LINKED ISSUE #719: need better indicator for loading (spinner)
- Fidget Spinners

### LINKED ISSUE #731: encapsulation not using internal functions
Instead of calling "treehouses" before commands. We could just call the commands themselves since cli.sh sources the files. Depends on order of sourcing but should be able to change this:

default.sh
```
  treehouses tor destroy > "$LOGFILE"
```
To this:
```
  tor destroy > "$LOGFILE"
```

### PR DESCRIPTION
**Pull request by LordJashin32**
Fixes #719 
Fixes #731
- [x] Runs in background
- [x] Dynamic cursor
- [x] Terminates on Signals (close, ctrl+c, exit, etc)
- [x] treehouses remote app compatibility
- [x] Fixed encapsulation code compatibility
- [x] Works with Crontab
- [ ] Vagrant support
- [ ] Dogi finally merge it ;)

### CODE REVIEW

**Comment by vmnet8** [comment]
it works especially when I run the command such as speedtest, it shows the spinner all the time correctly.
cool.

**Comment by LordJashin32** [comment]
Don't merge this yet. The only problem right now is setting the terminal cursor back to normal when pressing "ctrl +c". I have to run a few more tests and update this code a bit but this is a good start. Cheers.

**Comment by LordJashin32** [comment]
Okay this is ready to go. I can't find any more issues with it in testing. Cheers.

**Comment by LordJashin32** [comment]
added comments for people to learn what's going on here. Cheers.

**Comment by LordJashin32** [comment]
Going to update in a new PR

**Pull request closed without merging**
