### PR TITLE
`treehouses tether` (fixes #1316)

### LINKED ISSUE #1316: how to use `usb0` in network phone tether stuff
fix `treehouses networkmode`
fix `treehouses networkmode info`
with and without `ap` interface

### PR DESCRIPTION
**Pull request by darthnoward**
fixes #1316

### CODE REVIEW

**Comment by LordJashin32** [comment]
@darthnoward . @dogi requests that you make sure your git config is set so your commits come up as your picture. 

Also I think the code climate issues can be fixed pretty easily like so `if ! grep -q usb0 /var/lib/dhcp/*.lease; then`

**Comment by LordJashin32** [comment]
Didn't work for me. 
https://prnt.sc/sqvh8u

**Comment by darthnoward** [comment]
If two interfaces are being used at the same time, wlan0 is often prioritized over usb0.
In the latest commit I use ``` ip route get 8.8.8.8 ``` to determine which interface is being used.

```
$ ./cli.sh networkmode
wifi
```
connect to phone and enable tethering in setting
```
$ ./cli.sh networkmode
wifi

$ ./cli.sh tether
...Enabled.

$ ./cli.sh networkmode
wifi

# disconnect wifi will switch to usb0 interface
$ pkill wpa_supplicant
$ ./cli.sh networkmode
tether
```
after reboot
```
$ ./cli.sh networkmode
wifi
```

**Comment by LordJashin32** [comment]
the whole networking stack just needs a good cleansing and expanding. Need to be able to change priority of networkmodes. Owell. Will try this again in a bit and post back.

**Pull request merged**
