### PR TITLE
README.md table (fixes #906)

### LINKED ISSUE #906: README.md change to table
Possible solution to the current mess that is README.md -> change code block to a table.

### PR DESCRIPTION
**Pull request by kjong**
Fixes #906

### CODE REVIEW

**Comment by LordJashin32** [comment]
I still really like this but I wonder if maybe a tree, or something else would be even better. Its hard to show the sub commands going deeper and deeper within just 2 boxes. Or etc.

**Comment by kjong** [comment]
A tree would be interesting. Would it be possible to represent a tree in markdown?

Maybe something like [this](https://stackoverflow.com/questions/19699059/representing-directory-file-structure-in-markdown-syntax)?

**Comment by LordJashin32** [comment]
> A tree would be interesting. Would it be possible to represent a tree in markdown?
> 
> Maybe something like [this](https://stackoverflow.com/questions/19699059/representing-directory-file-structure-in-markdown-syntax)?

Yeah I think I'll try it out. I think we can get this to describe the services as well as their commands if we format it correctly.

**Comment by LordJashin32** [comment]
After rethinking it. I don't think there is a way to keep it condensed and simple 1 page. If we do tree or table we lose that. 

With that said i figured out how to improve my other readme PR.

**Comment by LordJashin32** [comment]
As much as it may look crappy. Maybe we should do these:
<details>
  <summary>Spoiler warning</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>

**Pull request closed without merging**
