### PR TITLE
treehouses services url (fixes #833)

### LINKED ISSUE #833: treehouses services <service> url improvements?
```
root@treehouses:~/cli# ./cli.sh services couchdb url tor
Error: there are no tor ports added.
'cli.sh add [localPort]' to add a port and be able to use the service

root@treehouses:~/cli# ./cli.sh services couchdb url
unknown command
```

both of the answers are not optimal

### PR DESCRIPTION
**Pull request by LordJashin32**
Fixes #833
In favor of ```treehouses services <service_name> url``` to get both instead.
Or we can keep both and do "".

### CODE REVIEW

**Comment by vmnet8** [comment]
```pi@treehouses:~/git_repo/cli $ ./cli.sh services planet url
:80
:2200
Error: there are no tor ports added.
'cli.sh add [localPort]' to add a port and be able to use the service
```
it works

**Comment by kjong** [comment]
I'm not sure if @dogi wants to change the command itself, or add a more detailed error message.

Although logically, there isn't any reason for `treehouses services <service> url` to be an invalid command.

So we could go with @LordJashin32's approach (`url`) and also keep the `url both` command.

`elif [ "$command_option" = "both" ] || [ "$command_option" = "" ]; then`

**Comment by kjong** [comment]
Side-note, you might want to start including "Fixes ####" in the actual body of the pull request. GitHub doesn't seem to automatically pick up any of the fixes keywords in the titles. Saves you from having to go through all the issues and close them manually after merging.

**Comment by LordJashin32** [comment]
> Side-note, you might want to start including "Fixes ####" in the actual body of the pull request. GitHub doesn't seem to automatically pick up any of the fixes keywords in the titles. Saves you from having to go through all the issues and close them manually after merging.

Thanks for the heads up. I guess we don't need to put it in the titles anymore. Github doing loop de loops.

**Pull request merged**
