### PR TITLE
from pirateship to treehouses

### PR DESCRIPTION
**Pull request by TerrenceEJ**

### CODE REVIEW

**Comment by TerrenceEJ** [comment]
Yeah, it looks right

**Comment by TerrenceEJ** [comment]
that doesn't seem right on 2nd look, actually. I'll look more into it

**Comment by i5o** [comment]
Still wondering if this is the output we want. I'm using `treehouses bridge` 

```
pi@raspberrypi:~/cli $ git log -1
commit 2921307da1251cb7ea310dd9418276245779de03
Author: Terrence Eldred-Jones <terrencejones0820@gmail.com>
Date:   Mon May 28 22:29:07 2018 -0400

    loop for string instead
pi@raspberrypi:~/cli $ iwconfig wlan0
wlan0     IEEE 802.11  ESSID:"Chocolate"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 14:CC:20:8A:35:42   
          Bit Rate=24 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=67/70  Signal level=-43 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

pi@raspberrypi:~/cli $ ./cli.sh checksignal
Chocolate"  
pi@raspberrypi:~/cli $ 
```

**Comment by i5o** [comment]
```
root@raspberrypi:/home/pi# treehouses wifi Chocolate fosforito
password network
root@raspberrypi:/home/pi# treehouses default^C
root@raspberrypi:/home/pi# cd cli/
root@raspberrypi:/home/pi/cli# iwconfig wlan0
wlan0     IEEE 802.11  ESSID:"Chocolate"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 14:CC:20:8A:35:42   
          Bit Rate=65 Mb/s   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=66/70  Signal level=-44 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

root@raspberrypi:/home/pi/cli# ./cli.sh checksignal
Chocolate"  
root@raspberrypi:/home/pi/cli# 
```

**Comment by i5o** [comment]
@TerrenceEJ I was wondering if you have the output or something that you could share with me, I can take a look on how to gather the data/proper one once I know the desired output :)

Good job on the code by the way.

**Comment by TerrenceEJ** [comment]
I'm trying to get it so we just get 
`Signal level=-x`

**Comment by i5o** [comment]
thanks Terrence, I'll follow up with a new pull request with a branch rebased onto master

**Comment by i5o** [comment]
```
pi@raspberrypi:~ $ iwconfig wlan0 | sed -n 's/.*\(Signal level=-.*\) dBm/\1/p'
Signal level=-41  
pi@raspberrypi:~ $ 
```

**Pull request closed without merging**
