### PR TITLE
`treehouses services <service>` file check (fixes #879)

### LINKED ISSUE #879: treehouses services check if file exists
Waiting for #893

### PR DESCRIPTION
**Pull request by kjong**
Fixes #879

```
root@kjong:~/cli# ./cli.sh services netdata start
Starting netdata ... done
netdata started
root@kjong:~/cli# rm /srv/netdata/netdata.yml
root@kjong:~/cli# ./cli.sh services netdata stop
ERROR: /srv/netdata/netdata.yml not found
try running 'cli.sh services netdata install' first
root@kjong:~/cli# ./cli.sh services netdata install
Pulling netdata ... done
netdata installed
root@kjong:~/cli# ./cli.sh services netdata stop
Stopping netdata_netdata_1 ... done
netdata stopped
```

Don't need checks for `port`, `info`, `size`, or `icon` since they're caught by `check_available_services`:
```
root@kjong:~/cli# rm services/install-netdata.sh
root@kjong:~/cli# ./cli.sh services netdata port
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@kjong:~/cli# ./cli.sh services netdata info
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@kjong:~/cli# ./cli.sh services netdata size
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@kjong:~/cli# ./cli.sh services netdata icon
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
```

### CODE REVIEW

**Comment by LordJashin32** [comment]
Not sure if this works or not. But here is the tests from me. Services.bats ran fine. 
```bash
root@raspberrypi:~/cli# ./cli.sh services JackSkellington port
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services JackSkellington info
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services JackSkellington size
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services JackSkellington icon
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services JackSkellington start
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services JackSkellington stop
ERROR: unknown service
try running 'cli.sh services available' to see the list of available services
root@raspberrypi:~/cli# ./cli.sh services netdata install
Pulling netdata ... done
netdata installed
root@raspberrypi:~/cli# ./cli.sh services netdata stop
netdata not found
root@raspberrypi:~/cli# ls /srv/netdata
autorun  netdata.yml
root@raspberrypi:~/cli# ./cli.sh services netdata start
netdata not found
root@raspberrypi:~/cli# ./cli.sh services netdata cleanup
service autorun set to false
Removing network netdata_default
WARNING: Network netdata_default not found.
Removing image netdata/netdata
netdata stopped and removed
netdata cleaned up
root@raspberrypi:~/cli# ./cli.sh services netdata install
Pulling netdata ... downloading (66.8%)
^CERROR: Aborting.
retrying pull
Pulling netdata ...
^CERROR: Aborting.
retrying pull
ERROR: cannot pull docker image
root@raspberrypi:~/cli# ./cli.sh services netdata start
netdata not found
root@raspberrypi:~/cli# ./cli.sh services netdata install
Pulling netdata ... done
netdata installed
root@raspberrypi:~/cli# git status
On branch services-check-file
Your branch is up to date with 'origin/services-check-file'.

nothing to commit, working tree clean
root@raspberrypi:~/cli#

```

**Comment by LordJashin32** [comment]
```
root@raspberrypi:~/cli# git pull
Already up to date.
root@raspberrypi:~/cli# git fetch
root@raspberrypi:~/cli# git checkout services-check-file
Branch 'services-check-file' set up to track remote branch 'services-check-file' from 'origin'.
Switched to a new branch 'services-check-file'
root@raspberrypi:~/cli# ./cli.sh services netdata install
Pulling netdata ... done
netdata installed
root@raspberrypi:~/cli# ./cli.sh services netdata start
netdata not found
root@raspberrypi:~/cli#

```

**Comment by LordJashin32** [comment]
Idk why this doesn't work for me but here it is on fresh 125 image
```
root@treehouses:~/cli# git checkout services-check-file
Branch 'services-check-file' set up to track remote branch 'services-check-file' from 'origin'.
Switched to a new branch 'services-check-file'
root@treehouses:~/cli# services netdata start
-bash: services: command not found
root@treehouses:~/cli# ./cli.sh services netdata start
netdata not found
root@treehouses:~/cli# ./cli.sh services netdata stop
netdata not found
root@treehouses:~/cli# ./cli.sh services netdata install
Pulling netdata ... done
netdata installed
root@treehouses:~/cli# ./cli.sh services netdata stop
netdata not found
root@treehouses:~/cli# ./cli.sh image
release-125
root@treehouses:~/cli# ./cli.sh version
1.16.20
root@treehouses:~/cli#

```

**Comment by kjong** [comment]
You have to do `install` then `up`. After that you can do `start` or `stop`.
I guess I could add a message saying to try `up` first.

**Pull request merged**
