### PR TITLE
treehouses services secunda

### PR DESCRIPTION
**Pull request by kjong**
http://download.treehouses.io/experiment/treehouse-services2-1.img.gz

Use this image when testing

## Currently Available Services
* Planet (port 80)
* Kolibri (port 8080)
* Nextcloud (port 8081)
* Pi-hole (port 8053)
* **WIP** Moodle (port 8082)

## Functions
* `available` - lists services available to be installed / run
* `installed` - lists installed services
* `running` - lists running services
* `up` - build and start the service
* `down` - stop and remove the service
* `start` - start the service
* `stop` - stop the service
* `autorun` - sets service autorun to true or false (based on autorun file in `/boot/autorun`)
* `ps` - lists the containers related to the specified service

## Examples
`./cli.sh services2 available`
`./cli.sh services2 installed`
`./cli.sh services2 running`
`./cli.sh services2 planet up` - builds and starts the planet service
`./cli.sh services2 planet autorun` - outputs true if the planet service is set to autorun, false otherwise
`./cli.sh services2 planet autorun true` - sets the planet service to autorun
`./cli.sh services2 planet ps` - lists the containers related to planet

## Potential Functions?
* `./cli.sh services2 autorun` - lists all services and true or false for each

## WIP
* ~Change base autorun file in `builder` to match the new format (will fix issues with `planet` autorun)~ Fixed in experimental image
* Add tab completion

## Known Issues
* Attempting to start a new service (ie. creating a new tor port) while connected to tor will kick you off your tor connection
* Attempting to add a service to autorun without first building it causes issues with missing yml files

### CODE REVIEW

**Comment by kjong** [comment]
> is this commit completed yet?

All the functionality is ready to be tested.
I will be adding more services such as pihole in the future.

**Comment by kjong** [comment]
Added pihole service.

**Comment by irisb1701** [comment]
Everything looks good
```
root@planet:/home/vagrant/cli# ./cli.sh services2 running
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                        NAMES
e39bcdd3d6e7        treehouses/planet:local    "/bin/sh -c ./docker…"   3 months ago        Up 8 weeks          0.0.0.0:80->80/tcp                           planet_planet_1
da65f8423d85        treehouses/couchdb:2.3.0   "tini -- /docker-ent…"   3 months ago        Up 8 weeks          4369/tcp, 9100/tcp, 0.0.0.0:2200->5984/tcp   planet_couchdb_1

root@planet:/home/vagrant/cli# ./cli.sh services2 kolibri up
adding port 8080...
Success: the port has been added
yml file created
Creating network "kolibri_default" with the default driver
Pulling kolibri (treehouses/kolibri:)...
latest: Pulling from treehouses/kolibri
9d48c3bd43c5: Pull complete
b454f76b59d4: Pull complete
f239b7642fff: Pull complete
8e1ef6529d4d: Pull complete
d3b0519534f6: Pull complete
Digest: sha256:89dc5b39f9166d03ff11bfcb8999fc9598be3e62a25911adabd305f980b68672
Status: Downloaded newer image for treehouses/kolibri:latest
Creating kolibri_kolibri_1 ... done
kolibri built and started

root@planet:/home/vagrant/cli# ./cli.sh services2 running
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                        NAMES
d47b8c5a02a8        treehouses/kolibri         "/bin/sh -c './kolib…"   53 seconds ago      Up 50 seconds       0.0.0.0:8080->8080/tcp                       kolibri_kolibri_1
e39bcdd3d6e7        treehouses/planet:local    "/bin/sh -c ./docker…"   3 months ago        Up 8 weeks          0.0.0.0:80->80/tcp                           planet_planet_1
da65f8423d85        treehouses/couchdb:2.3.0   "tini -- /docker-ent…"   3 months ago        Up 8 weeks          4369/tcp, 9100/tcp, 0.0.0.0:2200->5984/tcp   planet_couchdb_1
root@planet:/home/vagrant/cli# 
```

only question is for 
```
root@planet:/home/vagrant/cli# ./cli.sh services2 planet autorun
false
```
I could be wrong but I thought planet was automatically set to autorun

**Comment by kjong** [comment]
> only question is for
> 
> ```
> root@planet:/home/vagrant/cli# ./cli.sh services2 planet autorun
> false
> ```
> 
> I could be wrong but I thought planet was automatically set to autorun

I'll have to flash a new image and take a look at how the autorun file is set originally.
The way I wrote my autorun stuff might be overwriting it.

**Comment by dogi** [comment]
https://github.com/treehouses/builder/blob/master/autorunonce#L145-L158
replace this with `treehouses service2 planet ...`

**Comment by kjong** [comment]
http://download.treehouses.io/experiment/treehouse-services2-0.img.gz

Use this image when testing

**Comment by Nida8930** [comment]
Everything seems to be working correctly on both the rpi3 and rpi4. I did not experience any issues with `./cli.sh services2 planet autorun`, it appeared to work as intended for each of the services. 

Good work.

**Comment by LordJashin32** [comment]
Haven't tried on new image but all the functions work except auto run just won't change to true. But since you focused on that already I'll just approve this. RPi4 tested. Was able to do all commands its just setting autorun to true wouldn't update it. Anyway, Cheers.

**Comment by kjong** [comment]
> Haven't tried on new image but all the functions work except auto run just won't change to true. But since you focused on that already I'll just approve this. RPi4 tested. Was able to do all commands its just setting autorun to true wouldn't update it. Anyway, Cheers.

@LordJashin32 Autorun not changing is fixed in the experimental image linked above.

**Comment by kjong** [comment]
@hiroTochigi So the problem with that scenario is that the yml files (if required) are created when the services are first created. It looks like you just added them to the autorun file without having created the services first.

I'm thinking that the best way around this is to check if the yml files are present when adding the service to the autorun file and if they aren't to create them.

**Comment by hiroTochigi** [comment]
> @hiroTochigi So the problem with that scenario is that the yml files (if required) are created when the services are first created. It looks like you just added them to the autorun file without having created the services first.
> 
> I'm thinking that the best way around this is to check if the yml files are present when adding the service to the autorun file and if they aren't to create them.

Yeah, I think that I did not understand the use case of autorun.

**Comment by kjong** [comment]
> Yeah, I think that I did not understand the use case of autorun.

It's still a good issue that we probably have to address in the future.

**Pull request merged**
