### PR TITLE
added logging to /var/log/treehouses.log

### LINKED ISSUE #169: I do not think we should be sending stdout and stderr to /dev/null
If something is broken we'd never know

https://github.com/treehouses/cli/blob/d6b49c656111b3e5c44d031e04832c318425dfc0/modules/globals.sh#L14-L17

### PR DESCRIPTION
**Pull request by 4ndrej**
added logging to /var/log/treehouses.log (+logrotate config)
for start|stop|enable|disable service
this fixes #169

### CODE REVIEW

**Comment by 4ndrej** [comment]
@phamduchongan93 I am not sure what did you suggest

**Comment by phamduchongan93** [comment]
> @phamduchongan93 I am not sure what did you suggest

Yeah, let me clarify that. I hope that we can build `treehouses log view` command that can view the log files generated by your services since you generated a log file already. Thus, It will mitigate the need of ssh to the pi to troubleshoot simple issue.

**Comment by phamduchongan93** [comment]
I'm not going to ruin your clean PR by adding an extra module. But this is kind of the idea I'm heading.

**Comment by 4ndrej** [comment]
@phamduchongan93 well, I have no idea how to add `treehouses log view` command but I feel it should be another feature request

**Comment by LordJashin32** [comment]
Tested this on RPi4 image 116. No problems. Was able to get a log up with some output from ```treehouses bluetooth on``` . Its possible we can extend this to all our code that points to the void and see if there is any silent errors going on that can be fixed.

**Pull request closed without merging**
