### PR TITLE
update _treehouses to auto detect services (fixes # 1041)

### LINKED ISSUE #1041: build tab completion block for each `<service>` automatically out of services folder
```
treehouses services couchdb autorun
treehouses services couchdb autorun false
treehouses services couchdb autorun true
treehouses services couchdb cleanup
treehouses services couchdb down
treehouses services couchdb icon
treehouses services couchdb icon oneline
treehouses services couchdb info
treehouses services couchdb install
treehouses services couchdb port
treehouses services couchdb ps
treehouses services couchdb restart
treehouses services couchdb size
treehouses services couchdb start
treehouses services couchdb stop
treehouses services couchdb up
treehouses services couchdb url
treehouses services couchdb url local
treehouses services couchdb url tor
```
this for example is one block of many services

### PR DESCRIPTION
**Pull request by kjong**
Fixes #1041

### CODE REVIEW

**Comment by vmnet8** [comment]
```
pi@treehouses:~/git_repo/cli $ ./cli.sh services available 
couchdb
kolibri
mariadb
mastodon
moodle
netdata
nextcloud
ntopng
pihole
planet
portainer
privatebin
seafile
turtleblocksjs
pi@treehouses:~/git_repo/cli $ ./cli.sh services mariadb 
autorun  down     info     port     restart  start    up       
cleanup  icon     install  ps       size     stop     url      
pi@treehouses:~/git_repo/cli $ ./cli.sh services mariadb autorun 
false  true   
pi@treehouses:~/git_repo/cli $ ./cli.sh services mariadb url 
local  tor    
```

for mariadb, it looks good, but there is no ` icon oneline`

**Comment by LordJashin32** [comment]
we're just going to have to grep help.sh in order to do this instead. It doesn't matter if checkarm is used or not because its just auto completion anyway

**Comment by LordJashin32** [comment]
@kjong Should be good for you to finish. Cheers.

**Comment by LordJashin32** [comment]
Ready for merge. @dogi

**Pull request merged**
