### PR TITLE
treehouses services <service> install (fixes #692)

### LINKED ISSUE #692: treehouses services refactor
Refactor services to use one install script to install all required files for a single service.

Facilitates future accessibility/modularity?

### PR DESCRIPTION
**Pull request by kjong**
Fixes #692

Consolidates `<service>_autorun` and `<service>_yml.sh` into one `install_<service>.sh`

Removes `<service>_autorun` and `<service>_yml.sh` files

`install_<service>.sh` creates files for:
* yml
* ports
* size
* info
* autorun

### Changes
* Service installation process changed to two-step process:
`services <service> install` -> creates required files (yml(s), ports, size, info, autorun) in `/srv/<service>/` and **pulls image from docker hub**
`services <service> up` -> creates service using pulled image, **no longer pulls image at this step**, **no longer overwrites yml(s) at this step**
* `available` now searches `$TEMPLATES/services/install-scripts/` to see what install scripts are available to be installed
* `installed` now uses `docker images` instead of `docker ps`
* `down`, `start`, `stop` no longer requires adding cases manually, instead uses `check_available_services` to automatically check for available services
* `info` no longer hardcoded
* `check_space` changed to hardcoded sizes
* `ports` no longer hardcoded

### Todo
- [x] add `docker pull` to `install` (rather than waiting for pull during `up`)
- [x] fix `treehouses services available`
- [x] fix `treehouses services ports`
- [x] fix `treehouses services installed`
- [x] rework cases so you don't have to add each service
- [x] update help
- [x] planet install?
- [x] available and installed intersection
- [x] ntopng
- [x] mastodon
- [ ] pre-install config files (eg. info)?

### CODE REVIEW

**Comment by LordJashin32** [comment]
I would do it in this naming scheme personally after thinking about it : install, remove, start, stop. Those seem the most intuitive to me but that's totally up to you. I think this is a great idea to start cutting down on the size of services.sh

**Comment by kjong** [comment]
> I would do it in this naming scheme personally after thinking about it : install, remove, start, stop. Those seem the most intuitive to me but that's totally up to you. I think this is a great idea to start cutting down on the size of services.sh .
> EDIT: I really like the checkboxes I forgot you could do that.

I was also thinking about merging up and start but it seems like it doesn't hurt to have them both.

**Comment by LordJashin32** [comment]
Test run (Looking good so far):
```
pi@treehouses:~/Public/cli $ sudo ./cli.sh services nextcloud install
Pulling nextcloud ... done                                                                                              nextcloud installed
pi@treehouses:~/Public/cli $ sudo ./cli.sh services available
kolibri
moodle
nextcloud
pihole
planet
portainer
privatebin
pi@treehouses:~/Public/cli $ sudo ./cli.sh services installed
nextcloud planet portainer couchdb
pi@treehouses:~/Public/cli $ sudo ./cli.sh services nextcloud info
https://github.com/nextcloud

"A safe home for all your data. Access & share your files, calendars,
contacts, mail & more from any device, on your terms."
pi@treehouses:~/Public/cli $ sudo ./cli.sh services ports
nextcloud                  port 8081
planet                     port 80, 2200
pi@treehouses:~/Public/cli $ sudo ./cli.sh services nextcloud down
Removing network nextcloud_default
WARNING: Network nextcloud_default not found.
nextcloud stopped and removed
pi@treehouses:~/Public/cli $ sudo ./cli.sh services nextcloud up
Creating network "nextcloud_default" with the default driver
Creating nextcloud_nextcloud_1 ... done                                                                                 nextcloud built and started
pi@treehouses:~/Public/cli $ sudo ./cli.sh services running
nextcloud planet
```

**Comment by vmnet8** [comment]
```
pi@treehouses:~/git_repo/cli $ ./cli.sh services  installed
openwrt debian planet portainer ntopng sdk rootfs couchdb
```
use ```docker images``` will show some docker images which doesn't belong to services.  for example, such openwrt and debian.

**Comment by kjong** [comment]
> ```
> pi@treehouses:~/git_repo/cli $ ./cli.sh services  installed
> openwrt debian planet portainer ntopng sdk rootfs couchdb
> ```
> 
> use `docker images` will show some docker images which doesn't belong to services. for example, such openwrt and debian.

Could you please test this again?
I added some code to filter out the irrelevant images.

**Comment by LordJashin32** [comment]
Seems to work for me. I installed ntopng. Used most of the commands. I guess there's not supposed to be a way to uninstall from srv/ folder because we are using install as a permanent thing instead of pulling image everytime?

I would say we probably need to think about if somebody uninstalls the CLI. We need to remove stuff in srv/ directory then for them.

**Comment by kjong** [comment]
> uninstall srv/ directories on CLI uninstall?

I was planning on it, but thought it might not be necessary.

**Pull request merged**
