### PR TITLE
treehouses discover mac (fixes #580)

### PR DESCRIPTION
**Pull request by vmnet8**
test:
./cli discover mac mac_address ( for example 00:00:17:15:a0:b0 )

### CODE REVIEW

**Comment by pattanawadee88** [comment]
```
root@treehouses:~/cli# ./cli.sh discover mac dc:a6:32:08:ae:d0
Valid mac address
 We can't find  ip address with this mac address
```

**Comment by vmnet8** [comment]
> ```
> root@treehouses:~/cli# ./cli.sh discover mac dc:a6:32:08:ae:d0
> Valid mac address
>  We can't find  ip address with this mac address
> ```

Thank you Pat for testing.
I will modify the output, let it clearly.

**Comment by xavierh93** [comment]
Couldn't get it to work for me
Screen Shot 2019-11-15 at 9 58 41 PM

**Comment by pattanawadee88** [comment]
```
root@treehouses:~/cli# ./cli.sh discover mac 98:01:a7:94:47:7b
 192.168.1.156
```

**Pull request merged**
